plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/homme.maktub/Apps Moviles/etiove/web"
publishOrigin = "config"
commandOrigin = "ui"
command = "expo export -p web"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]