plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/homme.maktub/Apps Moviles/etiove/web"
publishOrigin = "config"
commandOrigin = "ui"
command = "expo export -p web"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/blog"
to = "/blog/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/404.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]