export function buildCommunityCategoriesViewProps({
  s,
  gamification,
  getAchievementDefs,
  forumCategories,
  categoryRowAnimsRef,
  getPressAnim,
  categoryPressAnimsRef,
  handleOpenCategory,
  animatePressIn,
  animatePressOut,
}) {
  return {
    s,
    gamification,
    getAchievementDefs,
    forumCategories,
    categoryRowAnimsRef,
    getPressAnim,
    categoryPressAnimsRef,
    handleOpenCategory,
    animatePressIn,
    animatePressOut,
  };
}

export function buildCommunityThreadListViewProps({
  s,
  PremiumBadge,
  forumCategory,
  setForumCategory,
  handleOpenCreate,
  forumSort,
  setForumSort,
  forumLoading,
  forumThreadsByCategory,
  forumError,
  formatRelativeTime,
  threadListEnterAnim,
  skeletonShimmerAnim,
  threadRowAnimsRef,
  getPressAnim,
  threadPressAnimsRef,
  animatePressIn,
  animatePressOut,
  handleOpenThread,
}) {
  return {
    s,
    PremiumBadge,
    forumCategory,
    setForumCategory,
    handleOpenCreate,
    forumSort,
    setForumSort,
    forumLoading,
    forumThreadsByCategory,
    forumError,
    formatRelativeTime,
    threadListEnterAnim,
    skeletonShimmerAnim,
    threadRowAnimsRef,
    getPressAnim,
    threadPressAnimsRef,
    animatePressIn,
    animatePressOut,
    handleOpenThread,
  };
}

export function buildCommunityThreadDetailViewProps({
  s,
  theme,
  PremiumBadge,
  forumThread,
  setForumThread,
  setForumReplyTo,
  forumThreadScrollRef,
  hasUserVotedForoItem,
  hasUserReportedForoItem,
  isForumOwner,
  isAdmin,
  isStaff,
  abrirMenuAutorForo,
  votarEnForo,
  reportarForo,
  formatRelativeTime,
  forumTopReplies,
  forumRepliesByThread,
  handleReplyPress,
  composerEnterAnim,
  forumReplyTo,
  forumReplyInputRef,
  forumReplyText,
  setForumReplyText,
  handleSendReply,
  forumSendingReply,
}) {
  return {
    s,
    theme,
    PremiumBadge,
    forumThread,
    setForumThread,
    setForumReplyTo,
    forumThreadScrollRef,
    hasUserVotedForoItem,
    hasUserReportedForoItem,
    isForumOwner,
    isAdmin,
    isStaff,
    abrirMenuAutorForo,
    votarEnForo,
    reportarForo,
    formatRelativeTime,
    forumTopReplies,
    forumRepliesByThread,
    handleReplyPress,
    composerEnterAnim,
    forumReplyTo,
    forumReplyInputRef,
    forumReplyText,
    setForumReplyText,
    handleSendReply,
    forumSendingReply,
  };
}

export function buildCommunityCreateModalProps({
  visible,
  s,
  theme,
  forumCategory,
  forumTitle,
  setForumTitle,
  forumBody,
  setForumBody,
  forumAccessLevel,
  setForumAccessLevel,
  forumPhoto,
  seleccionarFotoForo,
  forumSaving,
  handlePublishThread,
  closeCreateModal,
  onBackdropPress,
  createModalAnim,
}) {
  return {
    visible,
    s,
    theme,
    forumCategory,
    forumTitle,
    setForumTitle,
    forumBody,
    setForumBody,
    forumAccessLevel,
    setForumAccessLevel,
    forumPhoto,
    seleccionarFotoForo,
    forumSaving,
    handlePublishThread,
    closeCreateModal,
    onBackdropPress,
    createModalAnim,
  };
}

export function buildCommunityEditModalProps({
  visible,
  s,
  forumEditCollection,
  forumEditTitle,
  setForumEditTitle,
  forumEditBody,
  setForumEditBody,
  forumEditing,
  closeEditModal,
  handleSaveEdit,
  onBackdropPress,
  editModalAnim,
}) {
  return {
    visible,
    s,
    forumEditCollection,
    forumEditTitle,
    setForumEditTitle,
    forumEditBody,
    setForumEditBody,
    forumEditing,
    closeEditModal,
    handleSaveEdit,
    onBackdropPress,
    editModalAnim,
  };
}
