import useCommunityTabUi from './useCommunityTabUi';
import {
  buildCommunityCategoriesViewProps,
  buildCommunityCreateModalProps,
  buildCommunityEditModalProps,
  buildCommunityThreadDetailViewProps,
  buildCommunityThreadListViewProps,
} from '../../domain/community/viewProps';
import {
  getCommunityRoleFlags,
  getCommunityVisibleViews,
} from '../../domain/community/viewState';

export default function useCommunityTabComposition(props) {
  const {
    s,
    theme,
    PremiumBadge,
    perfil,
    gamification,
    getAchievementDefs,
    forumCategories,
    forumCategory,
    setForumCategory,
    forumThread,
    setForumThread,
    forumCreateOpen,
    setForumCreateOpen,
    forumLoading,
    forumThreadsByCategory,
    forumError,
    formatRelativeTime,
    forumThreadScrollRef,
    hasUserVotedForoItem,
    hasUserReportedForoItem,
    isForumOwner,
    abrirMenuAutorForo,
    votarEnForo,
    reportarForo,
    forumTopReplies,
    forumRepliesByThread,
    prepararRespuestaForo,
    setForumReplyTo,
    forumReplyTo,
    forumReplyInputRef,
    forumReplyText,
    setForumReplyText,
    enviarRespuestaForo,
    forumSendingReply,
    forumTitle,
    setForumTitle,
    forumBody,
    setForumBody,
    forumAccessLevel,
    setForumAccessLevel,
    forumPhoto,
    seleccionarFotoForo,
    crearHiloForo,
    forumSaving,
    forumEditOpen,
    setForumEditOpen,
    forumEditCollection,
    forumEditTitle,
    setForumEditTitle,
    forumEditBody,
    setForumEditBody,
    guardarEdicionForo,
    forumEditing,
    interactionFeedbackEnabled,
    interactionFeedbackMode,
  } = props;

  const ui = useCommunityTabUi({
    forumCategories,
    forumCategory,
    setForumCategory,
    forumThread,
    setForumThread,
    forumCreateOpen,
    setForumCreateOpen,
    forumLoading,
    forumThreadsByCategory,
    prepararRespuestaForo,
    enviarRespuestaForo,
    crearHiloForo,
    forumEditOpen,
    setForumEditOpen,
    guardarEdicionForo,
    interactionFeedbackEnabled,
    interactionFeedbackMode,
  });

  const { isAdmin, isStaff } = getCommunityRoleFlags(perfil);
  const { showCategories, showThreadList, showThreadDetail } = getCommunityVisibleViews({
    forumCategory,
    forumThread,
  });

  const categoriesViewProps = buildCommunityCategoriesViewProps({
    s,
    gamification,
    getAchievementDefs,
    forumCategories,
    categoryRowAnimsRef: ui.categoryRowAnimsRef,
    getPressAnim: ui.getPressAnim,
    categoryPressAnimsRef: ui.categoryPressAnimsRef,
    handleOpenCategory: ui.handleOpenCategory,
    animatePressIn: ui.animatePressIn,
    animatePressOut: ui.animatePressOut,
  });

  const threadListViewProps = buildCommunityThreadListViewProps({
    s,
    PremiumBadge,
    forumCategory,
    setForumCategory,
    handleOpenCreate: ui.handleOpenCreate,
    forumSort,
    setForumSort,
    forumLoading,
    forumThreadsByCategory,
    forumError,
    formatRelativeTime,
    threadListEnterAnim: ui.threadListEnterAnim,
    skeletonShimmerAnim: ui.skeletonShimmerAnim,
    threadRowAnimsRef: ui.threadRowAnimsRef,
    getPressAnim: ui.getPressAnim,
    threadPressAnimsRef: ui.threadPressAnimsRef,
    animatePressIn: ui.animatePressIn,
    animatePressOut: ui.animatePressOut,
    handleOpenThread: ui.handleOpenThread,
  });

  const threadDetailViewProps = buildCommunityThreadDetailViewProps({
    s,
    theme,
    PremiumBadge,
    forumThread,
    setForumThread,
    setForumReplyTo,
    forumThreadScrollRef,
    hasUserVotedForoItem,
    hasUserReportedForoItem,
    isForumOwner,
    isAdmin,
    isStaff,
    abrirMenuAutorForo,
    votarEnForo,
    reportarForo,
    formatRelativeTime,
    forumTopReplies,
    forumRepliesByThread,
    handleReplyPress: ui.handleReplyPress,
    composerEnterAnim: ui.composerEnterAnim,
    forumReplyTo,
    forumReplyInputRef,
    forumReplyText,
    setForumReplyText,
    handleSendReply: ui.handleSendReply,
    forumSendingReply,
  });

  const createModalProps = buildCommunityCreateModalProps({
    visible: forumCreateOpen,
    s,
    theme,
    forumCategory,
    forumTitle,
    setForumTitle,
    forumBody,
    setForumBody,
    forumAccessLevel,
    setForumAccessLevel,
    forumPhoto,
    seleccionarFotoForo,
    forumSaving,
    handlePublishThread: ui.handlePublishThread,
    closeCreateModal: ui.closeCreateModal,
    onBackdropPress: ui.handleCreateBackdropPress,
    createModalAnim: ui.createModalAnim,
  });

  const editModalProps = buildCommunityEditModalProps({
    visible: forumEditOpen,
    s,
    forumEditCollection,
    forumEditTitle,
    setForumEditTitle,
    forumEditBody,
    setForumEditBody,
    forumEditing,
    closeEditModal: ui.closeEditModal,
    handleSaveEdit: ui.handleSaveEdit,
    onBackdropPress: ui.handleEditBackdropPress,
    editModalAnim: ui.editModalAnim,
  });

  return {
    isAdmin,
    isStaff,
    showCategories,
    showThreadList,
    showThreadDetail,
    categoriesViewProps,
    threadListViewProps,
    threadDetailViewProps,
    createModalProps,
    editModalProps,
    ui,
  };
}
