import { StyleSheet } from 'react-native';

export const AUTH_COLORS = {
  primary: '#2f1d14',
  primaryText: '#fff9f1',
  accent: '#5d4030',
  surface: '#fffaf5',
  background: '#f6efe7',
  border: '#eadbce',
  muted: '#8f837a',
  text: '#1f140f',
};

const authScreenStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff' },
  authScroll: {
    padding: 24,
    paddingTop: 36,
    paddingBottom: 40,
    flexGrow: 1,
    justifyContent: 'center',
    backgroundColor: AUTH_COLORS.background,
  },
  authShell: { position: 'relative', gap: 22 },
  authAuraOne: {
    position: 'absolute',
    top: -28,
    right: -18,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(119, 82, 57, 0.09)',
  },
  authAuraTwo: {
    position: 'absolute',
    bottom: 90,
    left: -36,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255, 248, 241, 0.72)',
  },
  authBrandBlock: { paddingTop: 8, paddingBottom: 2, alignItems: 'center' },
  wordmark: {
    fontSize: 42,
    letterSpacing: 4,
    color: AUTH_COLORS.text,
    fontFamily: 'PlayfairDisplay_700Bold',
  },
  wordmarkSub: {
    color: AUTH_COLORS.accent,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2,
  },
  wordmarkTag: {
    marginTop: 6,
    fontSize: 13,
    color: '#7e6b5f',
  },
  authCard: {
    backgroundColor: AUTH_COLORS.surface,
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: AUTH_COLORS.border,
    shadowColor: '#3a2416',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  authKicker: {
    fontSize: 11,
    fontWeight: '800',
    color: '#8d6d58',
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: 10,
  },
  authTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: AUTH_COLORS.text,
    marginBottom: 8,
    fontFamily: 'PlayfairDisplay_700Bold',
  },
  authSub: {
    fontSize: 15,
    color: '#7e6b5f',
    marginBottom: 24,
    lineHeight: 22,
  },
  label: {
    color: '#836e61',
    marginBottom: 8,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#f8f1ea',
    borderWidth: 1,
    borderColor: '#e8dacd',
    color: '#221610',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  rememberToggle: {
    width: 46,
    height: 28,
    borderRadius: 14,
    padding: 3,
    backgroundColor: '#ddd4cb',
    justifyContent: 'center',
  },
  rememberToggleActive: {
    backgroundColor: AUTH_COLORS.accent,
  },
  rememberToggleKnob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#fffdf8',
  },
  rememberToggleKnobActive: {
    alignSelf: 'flex-end',
  },
  rememberText: { fontSize: 14, color: '#5f534b' },
  inlineNotice: {
    marginBottom: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e1cfbf',
    backgroundColor: '#f8efe6',
    padding: 14,
    gap: 8,
  },
  inlineNoticeTitle: {
    color: AUTH_COLORS.text,
    fontSize: 14,
    fontWeight: '800',
  },
  inlineNoticeText: {
    color: '#6c584a',
    fontSize: 13,
    lineHeight: 18,
  },
  inlineNoticeBtn: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#eadbce',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  inlineNoticeBtnText: {
    color: AUTH_COLORS.accent,
    fontSize: 12,
    fontWeight: '800',
  },
  primaryBtn: {
    backgroundColor: AUTH_COLORS.primary,
    borderRadius: 30,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  primaryBtnText: {
    color: AUTH_COLORS.primaryText,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 14,
    padding: 14,
    borderWidth: 1.2,
    borderColor: '#dcc8b7',
    borderRadius: 30,
    backgroundColor: '#f9f2ea',
  },
  secondaryBtnText: { color: AUTH_COLORS.accent, fontWeight: '700', fontSize: 15 },
  links: { marginTop: 20, gap: 12, alignItems: 'center' },
  link: { color: AUTH_COLORS.accent, fontSize: 14, fontWeight: '700' },
  linkMuted: { color: AUTH_COLORS.muted, fontSize: 14, fontWeight: '600' },
});

export default authScreenStyles;
