export default function buildMainScreenTabPropGroups({
  styles,
  theme,
  premiumAccent,
  premiumAccentDeep,
  components,
  keys,
  ui,
  domain,
  forum,
  bootstrap,
  gamification,
  profileSummary,
  profileTools,
  onLogout,
  appVersion,
  forumCategories,
}) {
  return {
    core: {
      s: styles,
      theme,
      premiumAccent,
      premiumAccentDeep,
      onLogout,
      appVersion,
      iconFaint: theme.icon.faint,
    },
    components,
    keys,
    navigation: {
      activeTab: ui.activeTab,
      setActiveTab: ui.setActiveTab,
      setScanning: ui.setScanning,
      setCafeDetalle: ui.setCafeDetalle,
      setTrendingFilters: ui.setTrendingFilters,
    },
    profile: {
      perfil: ui.perfil,
      setShowProfile: ui.setShowProfile,
      profileInitial: profileSummary.profileInitial,
      profileAlias: profileSummary.profileAlias,
      profileName: profileSummary.profileName,
      memberStatus: profileSummary.memberStatus,
      unlockedCount: profileSummary.unlockedCount,
      achievementTotal: profileSummary.achievementTotal,
      pendingAchievements: profileSummary.pendingAchievements,
      achievementProgress: profileSummary.achievementProgress,
      unlockedAchievements: profileSummary.unlockedAchievements,
      currentLevel: profileSummary.currentLevel,
      nextLevel: profileSummary.nextLevel,
      brandCardAnim: ui.brandCardAnim,
      brandCardTranslateY: profileSummary.brandCardTranslateY,
      brandCardScale: profileSummary.brandCardScale,
      brandProgressWidth: profileSummary.brandProgressWidth,
      flag: profileSummary.flag,
      newsletterHasEmail: profileSummary.newsletterHasEmail,
      newsletterEmail: profileSummary.newsletterEmail,
    },
    search: {
      busqueda: ui.busqueda,
      setBusqueda: ui.setBusqueda,
      busquedaMis: ui.busquedaMis,
      setBusquedaMis: ui.setBusquedaMis,
    },
    interaction: {
      favs: ui.favs,
      toggleFav: domain.toggleFav,
      interactionFeedbackSettings: bootstrap.interactionFeedbackSettings,
      guardarFeedbackInteracciones: bootstrap.guardarFeedbackInteracciones,
      guardarModoFeedbackInteracciones: bootstrap.guardarModoFeedbackInteracciones,
      onGamifyEvent: gamification.registrarEventoGamificacion,
    },
    newsletter: {
      newsletterState: bootstrap.newsletterState,
      guardarNewsletter: bootstrap.guardarNewsletter,
      newsletterLoading: bootstrap.newsletterLoading,
      newsletterSaving: bootstrap.newsletterSaving,
    },
    premium: {
      premium: domain.premium,
      gamification: gamification.gamification,
    },
    coffee: {
      cargando: domain.cargando,
      cargandoCafInicio: domain.cargandoCafInicio,
      errorCafInicio: domain.errorCafInicio,
      cafeteriasInicio: domain.cafeteriasInicio,
      cargarCafeteriasInicio: domain.cargarCafeteriasInicio,
      allCafes: domain.allCafes,
      filtrar: domain.filtrar,
      ultimosGlobal: domain.ultimosGlobal,
      topCafesVista: domain.topCafesVista,
      trendingCafes: domain.trendingCafes,
      ultimos100: domain.ultimos100,
      top100: domain.top100,
      cafesParaOfertas: domain.cafesParaOfertas,
      favCafes: domain.favCafes,
      misCafes: domain.misCafes,
      cafesFiltrados: domain.cafesFiltrados,
      eliminarCafe: domain.eliminarCafe,
      notebook: domain.notebook,
      abrirNuevaCata: domain.abrirNuevaCata,
      abrirOfertasCafe: domain.abrirOfertasCafe,
      abrirOfertaWeb: domain.abrirOfertaWeb,
    },
    offers: {
      ofertasPorCafe: ui.ofertasPorCafe,
      buscandoOfertaId: ui.buscandoOfertaId,
      openOfferCafeId: ui.openOfferCafeId,
      errorOfertas: ui.errorOfertas,
    },
    trending: {
      trendingFilters: ui.trendingFilters,
      setTrendingFilters: ui.setTrendingFilters,
    },
    community: {
      forumCategories,
      forumCategory: forum.forumCategory,
      setForumCategory: forum.setForumCategory,
      forumThread: forum.forumThread,
      setForumThread: forum.setForumThread,
      forumCreateOpen: forum.forumCreateOpen,
      setForumCreateOpen: forum.setForumCreateOpen,
      forumSort: forum.forumSort,
      setForumSort: forum.setForumSort,
      forumLoading: forum.forumLoading,
      forumThreadsByCategory: forum.forumThreadsByCategory,
      forumError: forum.forumError,
      formatRelativeTime: forum.formatRelativeTime,
      forumThreadScrollRef: ui.forumThreadScrollRef,
      hasUserVotedForoItem: forum.hasUserVotedForoItem,
      hasUserReportedForoItem: forum.hasUserReportedForoItem,
      isForumOwner: forum.isForumOwner,
      abrirMenuAutorForo: forum.abrirMenuAutorForo,
      votarEnForo: forum.votarEnForo,
      reportarForo: forum.reportarForo,
      forumTopReplies: forum.forumTopReplies,
      forumRepliesByThread: forum.forumRepliesByThread,
      prepararRespuestaForo: forum.prepararRespuestaForo,
      setForumReplyTo: forum.setForumReplyTo,
      forumReplyTo: forum.forumReplyTo,
      forumReplyInputRef: ui.forumReplyInputRef,
      forumReplyText: forum.forumReplyText,
      setForumReplyText: forum.setForumReplyText,
      enviarRespuestaForo: forum.enviarRespuestaForo,
      forumSendingReply: forum.forumSendingReply,
      forumTitle: forum.forumTitle,
      setForumTitle: forum.setForumTitle,
      forumBody: forum.forumBody,
      setForumBody: forum.setForumBody,
      forumAccessLevel: forum.forumAccessLevel,
      setForumAccessLevel: forum.setForumAccessLevel,
      forumPhoto: forum.forumPhoto,
      seleccionarFotoForo: forum.seleccionarFotoForo,
      crearHiloForo: forum.crearHiloForo,
      forumSaving: forum.forumSaving,
      forumEditOpen: forum.forumEditOpen,
      setForumEditOpen: forum.setForumEditOpen,
      forumEditCollection: forum.forumEditCollection,
      forumEditTitle: forum.forumEditTitle,
      setForumEditTitle: forum.setForumEditTitle,
      forumEditTarget: forum.forumEditTarget,
      setForumEditTarget: forum.setForumEditTarget,
      forumEditBody: forum.forumEditBody,
      setForumEditBody: forum.setForumEditBody,
      guardarEdicionForo: forum.guardarEdicionForo,
      forumEditing: forum.forumEditing,
      getUserLevel: profileTools.getUserLevel,
      getAchievementDefs: profileTools.getAchievementDefs,
      levels: profileTools.levels,
      gamification: gamification.gamification,
    },
  };
}
