import { Platform, StyleSheet } from 'react-native';

export default function createMainScreenStyles(THEME, PREMIUM_ACCENT, PREMIUM_ACCENT_DEEP) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: '#fff' },
    welcomeScreen: {
      flex: 1,
      backgroundColor: '#f6efe7',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    welcomeAuraOne: {
      position: 'absolute',
      top: 90,
      right: -20,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: 'rgba(119, 82, 57, 0.08)',
    },
    welcomeAuraTwo: {
      position: 'absolute',
      bottom: 80,
      left: -40,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: 'rgba(255, 248, 241, 0.76)',
    },
    welcomeCard: {
      width: '100%',
      borderRadius: 30,
      backgroundColor: '#fffaf5',
      borderWidth: 1,
      borderColor: '#eadbce',
      paddingVertical: 34,
      paddingHorizontal: 22,
      alignItems: 'center',
      shadowColor: '#3a2416',
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    welcomeTypeBox: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 130,
      gap: 6,
    },
    welcomeLineTop: {
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 3.2,
      color: '#5e4332',
      fontFamily: 'PlayfairDisplay_800ExtraBold',
    },
    welcomeLineBottom: {
      fontSize: 44,
      fontWeight: '900',
      letterSpacing: 4.2,
      color: '#1c120d',
      fontFamily: 'PlayfairDisplay_800ExtraBold',
    },
    welcomeTitle: {
      fontSize: 44,
      fontWeight: '900',
      letterSpacing: 4.2,
      color: '#1c120d',
      fontFamily: 'PlayfairDisplay_800ExtraBold',
    },
    welcomeSub: {
      fontSize: 10,
      color: '#6f5444',
      fontWeight: '800',
      letterSpacing: 2.1,
      textAlign: 'center',
      marginTop: 2,
    },
    welcomeCaption: {
      marginTop: 18,
      fontSize: 13,
      color: '#8a6d5b',
      fontWeight: '600',
      letterSpacing: 0.4,
      textAlign: 'center',
    },
    permScreen: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 32,
      gap: 16,
    },
    permTitle: { fontSize: 22, fontWeight: '700', color: '#111', textAlign: 'center' },
    permSub: { fontSize: 15, color: THEME.text.secondary, textAlign: 'center' },
    authScroll: {
      padding: 24,
      paddingTop: 36,
      paddingBottom: 40,
      flexGrow: 1,
      justifyContent: 'center',
      backgroundColor: '#f6efe7',
    },
    authShell: { position: 'relative', gap: 22 },
    authAuraOne: {
      position: 'absolute',
      top: -28,
      right: -18,
      width: 150,
      height: 150,
      borderRadius: 75,
      backgroundColor: 'rgba(119, 82, 57, 0.09)',
    },
    authAuraTwo: {
      position: 'absolute',
      bottom: 90,
      left: -36,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: 'rgba(255, 248, 241, 0.72)',
    },
    authBrandBlock: { paddingTop: 8, paddingBottom: 2 },
    authTitle: {
      fontSize: 30,
      fontWeight: '800',
      color: '#1f140f',
      marginBottom: 8,
      fontFamily: 'PlayfairDisplay_700Bold',
    },
    authSub: { fontSize: 15, color: '#7e6b5f', marginBottom: 24, lineHeight: 22 },
    authKicker: {
      fontSize: 11,
      fontWeight: '800',
      color: '#8d6d58',
      textTransform: 'uppercase',
      letterSpacing: 1.4,
      marginBottom: 10,
    },
    authCard: {
      backgroundColor: '#fffaf5',
      borderRadius: 28,
      padding: 22,
      borderWidth: 1,
      borderColor: '#eadbce',
      shadowColor: '#3a2416',
      shadowOpacity: 0.1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    authLinks: { marginTop: 20, gap: 12, alignItems: 'center' },
    authLink: { color: THEME.brand.accentDeep, fontSize: 14, fontWeight: '700' },
    authLinkMuted: { color: '#8f837a', fontSize: 14, fontWeight: '600' },
    rememberRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
    rememberText: { fontSize: 14, color: THEME.text.tertiary },
    authRememberText: { color: '#5f534b' },
    faceIdBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginTop: 16,
      padding: 14,
      borderWidth: 1.5,
      borderColor: THEME.brand.accentDeep,
      borderRadius: 30,
      backgroundColor: '#f9f2ea',
    },
    faceIdText: { color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
    authLabel: { color: '#836e61' },
    authInput: {
      backgroundColor: '#f8f1ea',
      borderWidth: 1,
      borderColor: '#e8dacd',
      color: '#221610',
    },
    authPrimaryBtn: {
      backgroundColor: THEME.brand.primary,
      borderRadius: 30,
      padding: 16,
      alignItems: 'center',
      marginTop: 8,
      shadowColor: THEME.brand.primary,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    authPrimaryBtnText: {
      color: THEME.brand.onPrimary,
      fontWeight: '800',
      fontSize: 15,
      letterSpacing: 0.3,
    },
    authSecondaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginTop: 14,
      padding: 14,
      borderWidth: 1.2,
      borderColor: '#dcc8b7',
      borderRadius: 30,
      backgroundColor: '#f9f2ea',
    },
    authSecondaryBtnText: { color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
    topBar: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 8, gap: 10 },
    homeBrandWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingTop: 2,
      paddingBottom: 2,
    },
    homeWordmark: {
      fontSize: 42,
      fontWeight: '900',
      letterSpacing: 4.2,
      color: '#1c120d',
      textShadowColor: 'rgba(111, 84, 68, 0.08)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 8,
      fontFamily: 'PlayfairDisplay_800ExtraBold',
    },
    homeLoverRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    homeLoverText: { fontSize: 10, fontWeight: '800', color: '#6f5444', letterSpacing: 2.2 },
    homeMiniSealOuter: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#c4a18a',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fcf7f1',
    },
    homeMiniSealMiddle: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: 'rgba(154, 121, 99, 0.4)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeMiniSealInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: '#8f6a53',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f2e7dc',
    },
    homeMiniSealText: { fontSize: 8, fontWeight: '900', color: '#6f5444', letterSpacing: 0.5 },
    wordmarkWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: 2,
      paddingTop: 4,
    },
    wordmarkCrest: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 3 },
    wordmarkMiniLabelWrap: { minWidth: 78, alignItems: 'center' },
    wordmarkMiniLabel: { fontSize: 9, fontWeight: '800', color: '#9a7963', letterSpacing: 2.2 },
    wordmarkSealOuter: {
      width: 38,
      height: 38,
      borderRadius: 19,
      borderWidth: 1,
      borderColor: '#c4a18a',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fcf7f1',
    },
    wordmarkSealMiddle: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: 'rgba(154, 121, 99, 0.38)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    wordmarkSeal: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: '#8f6a53',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f2e7dc',
    },
    wordmarkSealText: { fontSize: 11, fontWeight: '900', color: '#6f5444', letterSpacing: 1.1 },
    wordmark: {
      fontSize: 40,
      fontWeight: '900',
      letterSpacing: 4.2,
      color: '#1c120d',
      textShadowColor: 'rgba(111, 84, 68, 0.08)',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 8,
      fontFamily: 'PlayfairDisplay_800ExtraBold',
    },
    wordmarkSub: {
      fontSize: 10,
      color: '#8a6b57',
      fontWeight: '800',
      letterSpacing: 3.2,
      marginTop: -2,
    },
    wordmarkTag: {
      fontSize: 10,
      color: '#6f5444',
      fontWeight: '800',
      letterSpacing: 2.1,
      textAlign: 'center',
      marginTop: 2,
    },
    authWordmarkSub: { marginBottom: 10 },
    authWordmarkTag: { marginTop: 0 },
    locationPill: {
      position: 'relative',
      overflow: 'hidden',
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 10,
      minWidth: 210,
      backgroundColor: '#1f140f',
      borderWidth: 1,
      borderColor: '#4e3426',
      shadowColor: '#170d08',
      shadowOpacity: 0.24,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 5,
    },
    locationText: { fontSize: 15, fontWeight: '800', color: '#f8ead9', letterSpacing: 0.2 },
    brandPillContent: { gap: 6 },
    brandEyebrow: {
      fontSize: 9,
      fontWeight: '700',
      color: '#d6b89b',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    brandRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    brandMemberRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    brandMemberIdentity: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    brandMemberAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1.2,
      borderColor: 'rgba(255, 236, 220, 0.2)',
    },
    brandMemberAvatarFallback: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255, 248, 241, 0.1)',
      borderWidth: 1.2,
      borderColor: 'rgba(255, 236, 220, 0.14)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    brandMemberAvatarText: { color: '#fff1e4', fontSize: 15, fontWeight: '800' },
    brandMemberCopy: { flex: 1, gap: 2 },
    brandAlias: { fontSize: 14, fontWeight: '800', color: '#fff4ea' },
    brandName: { fontSize: 10, color: '#d2bead' },
    brandTitleWrap: { flex: 1, gap: 3 },
    brandLevelBadge: {
      backgroundColor: 'rgba(248, 225, 198, 0.12)',
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderColor: 'rgba(248, 225, 198, 0.18)',
    },
    brandLevelText: { fontSize: 10, fontWeight: '800', color: '#fff4ea' },
    brandXpText: { fontSize: 11, color: '#d4c1b1', fontWeight: '600' },
    brandMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    brandMetaText: { fontSize: 10, color: '#c9ab90' },
    brandProgressTrack: {
      height: 6,
      borderRadius: 999,
      backgroundColor: 'rgba(255, 244, 234, 0.12)',
      overflow: 'hidden',
    },
    brandProgressFill: { height: '100%', borderRadius: 999, backgroundColor: '#d18b4a' },
    brandStatsRow: { flexDirection: 'row', gap: 6 },
    brandStatCard: {
      flex: 1,
      backgroundColor: 'rgba(255, 248, 241, 0.06)',
      borderRadius: 12,
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderWidth: 1,
      borderColor: 'rgba(255, 234, 214, 0.08)',
      alignItems: 'center',
    },
    brandStatValue: { fontSize: 13, fontWeight: '800', color: '#fff1e4' },
    brandStatLabel: { fontSize: 9, color: '#cfb39a', marginTop: 1 },
    brandDecorOne: {
      position: 'absolute',
      top: -30,
      right: -20,
      width: 94,
      height: 94,
      borderRadius: 47,
      backgroundColor: 'rgba(209, 139, 74, 0.13)',
    },
    brandDecorTwo: {
      position: 'absolute',
      bottom: -48,
      left: -26,
      width: 98,
      height: 98,
      borderRadius: 49,
      backgroundColor: 'rgba(255, 244, 234, 0.06)',
    },
    brandTopRule: {
      position: 'absolute',
      top: 0,
      left: 14,
      right: 14,
      height: 1,
      backgroundColor: 'rgba(255, 238, 220, 0.18)',
    },
    profileBtn: { padding: 2 },
    profileAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: PREMIUM_ACCENT,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    profileAvatarText: { color: THEME.text.inverse, fontWeight: '700', fontSize: 16 },
    searchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginVertical: 10,
      backgroundColor: '#f5f5f5',
      borderRadius: 25,
      paddingHorizontal: 14,
      height: 44,
    },
    searchInput: { flex: 1, fontSize: 15, color: '#222', marginLeft: 8 },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginTop: 20,
      marginBottom: 2,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#111',
      fontFamily: 'PlayfairDisplay_700Bold',
    },
    sectionSub: {
      fontSize: 13,
      color: THEME.text.secondary,
      paddingHorizontal: 16,
      marginBottom: 14,
    },
    pageTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#111',
      marginBottom: 12,
      fontFamily: 'PlayfairDisplay_700Bold',
    },
    empty: { color: THEME.text.muted, textAlign: 'center', marginTop: 40, fontSize: 14 },
    packshotFrame: {
      backgroundColor: '#ffffff',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#f1ece4',
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    packshotInner: {
      width: '100%',
      height: '100%',
      backgroundColor: '#fff',
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    packshotImage: { width: '84%', height: '84%' },
    packshotHeroFrame: { width: '68%', height: '72%', borderRadius: 28, padding: 14 },
    packshotHeroImage: { width: '88%', height: '88%' },
    packshotCardFrame: { width: 132, height: 172, marginTop: 14, borderRadius: 18, padding: 10 },
    packshotCardImage: { width: '86%', height: '86%' },
    packshotListFrame: { width: 68, height: 88, borderRadius: 14, padding: 8 },
    packshotListImage: { width: '88%', height: '88%' },
    cardH: { width: 160, marginRight: 4 },
    cardHImg: {
      width: 160,
      height: 200,
      borderRadius: 10,
      backgroundColor: '#f8f7f4',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
      overflow: 'hidden',
    },
    cardHOrigin: { fontSize: 12, color: THEME.text.secondary, marginBottom: 2 },
    cardHName: { fontSize: 14, fontWeight: '700', color: '#111', lineHeight: 19 },
    cardHRating: { fontSize: 13, fontWeight: '600', color: PREMIUM_ACCENT },
    cardHVotos: { fontSize: 12, color: THEME.text.secondary },
    cardV: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'flex-start',
      marginBottom: 16,
      paddingBottom: 16,
      borderBottomWidth: 0.5,
      borderBottomColor: THEME.border.soft,
    },
    cardVImg: {
      width: 80,
      height: 100,
      borderRadius: 10,
      backgroundColor: '#f8f7f4',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      overflow: 'hidden',
    },
    cardVOrigin: { fontSize: 12, color: THEME.text.secondary, marginBottom: 2 },
    cardVName: { fontSize: 15, fontWeight: '700', color: THEME.text.primary, marginBottom: 5 },
    cardVNotas: { fontSize: 12, color: THEME.text.muted, marginTop: 5, lineHeight: 17 },
    offerHint: { fontSize: 12, color: '#666', marginTop: 8 },
    offerMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 3 },
    offerSourceBadge: {
      fontSize: 10,
      fontWeight: '800',
      color: '#fff',
      backgroundColor: '#111',
      borderRadius: 999,
      paddingHorizontal: 6,
      paddingVertical: 3,
    },
    badgeRed: {
      position: 'absolute',
      top: 8,
      left: 8,
      backgroundColor: PREMIUM_ACCENT,
      borderRadius: 12,
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    badgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
    rankRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 0.5,
      borderBottomColor: THEME.border.soft,
    },
    rankNum: { fontSize: 22, fontWeight: '700', color: '#ccc', width: 28 },
    rankName: { fontSize: 15, fontWeight: '600', color: '#111' },
    rankVotos: { fontSize: 12, color: THEME.text.secondary, marginTop: 2 },
    redBtn: {
      backgroundColor: THEME.brand.primary,
      borderRadius: 30,
      padding: 16,
      alignItems: 'center',
      marginTop: 8,
      borderWidth: 1,
      borderColor: THEME.brand.primaryBorder,
      shadowColor: THEME.brand.primary,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    redBtnText: {
      color: THEME.brand.onPrimary,
      fontWeight: '800',
      fontSize: 15,
      letterSpacing: 0.3,
    },
    bottomBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: THEME.surface.base,
      borderTopWidth: 0.5,
      borderTopColor: THEME.border.soft,
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 20,
      paddingTop: 10,
    },
    tabBtn: { flex: 1, alignItems: 'center', gap: 3 },
    tabLabel: { fontSize: 10, color: THEME.text.secondary },
    tabBadge: {
      position: 'absolute',
      top: -4,
      right: -8,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: THEME.brand.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBadgeText: { color: THEME.text.inverse, fontSize: 9, fontWeight: '700' },
    camBtn: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: THEME.brand.primary,
      borderWidth: 1.5,
      borderColor: THEME.brand.primaryBorderStrong,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -20,
      shadowColor: THEME.brand.primary,
      shadowOpacity: 0.34,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 8,
    },
    formScroll: { padding: 20, paddingTop: 52, paddingBottom: 50 },
    backRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 20 },
    backText: { color: '#d4a574', fontSize: 15 },
    formTitle: { fontSize: 26, fontWeight: '700', color: '#111', marginBottom: 20 },
    fotoEmpty: {
      backgroundColor: '#f5f5f5',
      borderRadius: 14,
      height: 140,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginBottom: 20,
    },
    fotoEmptyText: { color: THEME.text.muted, fontSize: 14 },
    fotoFull: { width: '100%', height: 200, borderRadius: 14, marginBottom: 8 },
    retake: { color: PREMIUM_ACCENT_DEEP, fontSize: 13, textAlign: 'right', marginBottom: 20 },
    label: {
      fontSize: 12,
      fontWeight: '600',
      color: THEME.text.secondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    input: {
      backgroundColor: '#f5f5f5',
      borderRadius: 12,
      padding: 14,
      fontSize: 15,
      color: '#111',
      marginBottom: 18,
    },
    forumCatCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: '#faf8f5',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#d4a574',
      padding: 14,
    },
    forumCatEmoji: { fontSize: 22 },
    forumCatTitle: { fontSize: 15, fontWeight: '800', color: '#1f140f' },
    forumCatDesc: { fontSize: 12, color: '#8b7355', marginTop: 2 },
    forumHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 8,
    },
    forumNewBtn: {
      backgroundColor: THEME.brand.primary,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    forumNewBtnText: { color: THEME.brand.onPrimary, fontWeight: '700', fontSize: 12 },
    forumSortRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
    forumSortChip: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: '#e0d0c1',
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: '#fff',
    },
    forumSortChipActive: { backgroundColor: '#2f1d14', borderColor: '#2f1d14' },
    forumSortText: { fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '700' },
    forumSortTextActive: { color: '#fff' },
    forumThreadCard: {
      backgroundColor: '#fff',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#ece2d8',
      padding: 12,
    },
    forumThreadTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: THEME.text.primary,
      marginBottom: 4,
    },
    forumThreadBody: { fontSize: 13, color: '#4a3f36', lineHeight: 20 },
    forumMetaRow: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    forumAuthorRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    forumAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#e9ddcf',
    },
    forumAvatarText: { fontSize: 12, fontWeight: '800', color: THEME.brand.accentDeep },
    forumAuthorName: { fontSize: 12, fontWeight: '700', color: THEME.text.primary },
    forumAuthorLevel: { fontSize: 10, color: THEME.brand.accentDeep, fontWeight: '700' },
    forumMetaText: { fontSize: 11, color: THEME.text.secondary },
    forumCountersRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 8 },
    forumCounter: { fontSize: 12, color: THEME.text.tertiary, fontWeight: '600' },
    forumMainPost: {
      marginTop: 4,
      backgroundColor: THEME.brand.soft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#e4d3c2',
      padding: 14,
    },
    forumMainPostHead: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 8,
    },
    forumMainPostImage: { marginTop: 8, width: '100%', height: 160, borderRadius: 10 },
    forumReplyCard: {
      marginBottom: 10,
      backgroundColor: '#fff',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#efe6dc',
      padding: 10,
    },
    forumChildReplyCard: {
      marginTop: 8,
      marginLeft: 14,
      backgroundColor: '#faf6f1',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#f0e6db',
      padding: 9,
    },
    forumActionBtn: {
      backgroundColor: '#f7efe6',
      borderWidth: 1,
      borderColor: '#e6d5c4',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    forumActionText: { fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '700' },
    forumActionBtnDisabled: { backgroundColor: '#f3f0eb', borderColor: '#e3ddd6' },
    forumActionTextDisabled: { color: '#a39a90' },
    forumMetaActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    forumDotsBtn: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f7efe6',
      borderWidth: 1,
      borderColor: '#e6d5c4',
    },
    forumComposerWrap: {
      borderTopWidth: 1,
      borderTopColor: '#e8ddd2',
      backgroundColor: '#fff',
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: Platform.OS === 'ios' ? 34 : 86,
    },
    forumReplyingTag: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#f5ece2',
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 7,
      marginBottom: 8,
    },
    forumReplyingText: { fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '600' },
    forumComposerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
    forumComposerInput: {
      flex: 1,
      minHeight: 42,
      maxHeight: 110,
      backgroundColor: '#f5f0e9',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#e3d8cc',
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: '#2a1d14',
    },
    forumSendBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: THEME.brand.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    forumModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
    forumModalCard: {
      backgroundColor: '#fff',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 18,
      borderWidth: 1,
      borderColor: '#ebdfd3',
    },
    forumCountText: {
      fontSize: 12,
      color: THEME.text.secondary,
      textAlign: 'right',
      marginTop: -8,
      marginBottom: 10,
    },
  });
}
