import { StyleSheet } from 'react-native';

const mas = StyleSheet.create({
  premiumCard: {
    position: 'relative',
    overflow: 'hidden',
    marginTop: 8,
    marginBottom: 18,
    backgroundColor: '#1f140f',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#4a3022',
  },
  premiumGlow: {
    position: 'absolute',
    width: 170,
    height: 170,
    borderRadius: 85,
    right: -44,
    top: -68,
    backgroundColor: 'rgba(209, 139, 74, 0.2)',
  },
  premiumGlowTwo: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    left: -30,
    bottom: -24,
    backgroundColor: 'rgba(255, 233, 210, 0.08)',
  },
  clubTag: {
    color: '#caa487',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  premiumTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  premiumIdentity: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  premiumAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.2,
    borderColor: 'rgba(255, 232, 212, 0.28)',
  },
  premiumAvatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 248, 241, 0.13)',
    borderWidth: 1.2,
    borderColor: 'rgba(255, 232, 212, 0.22)',
  },
  premiumAvatarText: { color: '#fff3e8', fontSize: 16, fontWeight: '800' },
  premiumAlias: { color: '#fff4ea', fontSize: 14, fontWeight: '800' },
  premiumName: { color: '#d8c0ad', fontSize: 12, marginTop: 1 },
  premiumLevelBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(250, 229, 206, 0.32)',
    backgroundColor: 'rgba(255, 248, 241, 0.1)',
  },
  premiumLevelText: { color: '#fff4ea', fontSize: 11, fontWeight: '700' },
  premiumExplain: { color: '#d8c0ad', fontSize: 12, lineHeight: 18, marginTop: 10 },
  premiumStatsRow: { flexDirection: 'row', gap: 8, marginTop: 14 },
  premiumStatCard: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 248, 241, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(250, 229, 206, 0.12)',
    paddingVertical: 8,
    alignItems: 'center',
  },
  premiumStatValue: { color: '#fff4ea', fontSize: 16, fontWeight: '800' },
  premiumStatLabel: { color: '#d0b8a4', fontSize: 10, marginTop: 2 },
  memberProgressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 8,
  },
  memberProgressText: { color: '#edd8c5', fontSize: 11, fontWeight: '700' },
  memberProgressBar: {
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 248, 241, 0.12)',
    overflow: 'hidden',
  },
  memberProgressFill: { height: '100%', borderRadius: 999, backgroundColor: '#d18b4a' },
  quickGrid: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  quickCard: { flex: 1, borderRadius: 16, padding: 14, borderWidth: 1 },
  quickCardDark: { backgroundColor: '#2a1a12', borderColor: '#4d3222' },
  quickCardSoft: { backgroundColor: '#f8efe6', borderColor: '#e9d8c7' },
  quickTitleDark: { marginTop: 8, color: '#fff3e8', fontSize: 14, fontWeight: '800' },
  quickSubDark: { marginTop: 3, color: '#d8bcaa', fontSize: 11 },
  quickTitle: { marginTop: 8, color: '#2d1d13', fontSize: 14, fontWeight: '800' },
  quickSub: { marginTop: 3, color: '#7d6a5f', fontSize: 11 },
  blockTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#876a56',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    marginTop: 4,
    marginBottom: 8,
  },
  listCard: {
    backgroundColor: '#fffaf6',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#eadbce',
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  achievementsCard: {
    backgroundColor: '#fffaf6',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#eadbce',
    padding: 12,
    gap: 8,
    marginBottom: 14,
  },
  blogCard: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#f8efe6',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e3cfbc',
    padding: 16,
    marginBottom: 14,
  },
  blogCardGlow: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 75,
    right: -40,
    top: -48,
    backgroundColor: 'rgba(143, 94, 59, 0.08)',
  },
  blogKicker: {
    color: '#8f5e3b',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  blogTitle: { color: '#24160f', fontSize: 18, fontWeight: '900', lineHeight: 22 },
  blogDesc: { color: '#6f5a4b', fontSize: 13, lineHeight: 19, marginTop: 8 },
  blogActionRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  blogActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 999,
    backgroundColor: '#2f1d14',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  blogActionText: { color: '#fff5eb', fontSize: 12, fontWeight: '800' },
  newsletterCard: {
    backgroundColor: '#fffaf6',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#eadbce',
    padding: 14,
    marginBottom: 14,
  },
  newsletterTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  newsletterTitleWrap: { flex: 1, paddingRight: 4 },
  newsletterTitle: { color: '#2c1c14', fontSize: 15, fontWeight: '800' },
  newsletterSub: { color: '#7d6a5f', fontSize: 12, lineHeight: 18, marginTop: 3 },
  newsletterMetaRow: { gap: 8, marginTop: 12 },
  newsletterStatusPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  newsletterStatusOn: { backgroundColor: '#f3e8db', borderColor: '#d6b798' },
  newsletterStatusOff: { backgroundColor: '#f6f1eb', borderColor: '#e6d8c9' },
  newsletterStatusText: { fontSize: 11, fontWeight: '800' },
  newsletterStatusTextOn: { color: '#6b4a37' },
  newsletterStatusTextOff: { color: '#8d7a6c' },
  newsletterEmail: { color: '#3a2a20', fontSize: 13, fontWeight: '600' },
  newsletterNote: { color: '#4a3428', fontSize: 12, lineHeight: 18, marginTop: 10 },
  newsletterBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: '#2f1d14',
    marginTop: 14,
  },
  newsletterBtnDisabled: { opacity: 0.45 },
  newsletterBtnText: { color: '#fff5eb', fontSize: 14, fontWeight: '800' },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: '#efe6dd',
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#f6ede3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: { fontSize: 15, fontWeight: '700', color: '#111' },
  sub: { fontSize: 12, color: '#8c847d', marginTop: 2 },
  achievementOn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f0e5d9',
    padding: 10,
  },
  achievementOff: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f8f3ee',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#efe4d7',
    padding: 10,
  },
  achievementIcon: { fontSize: 22 },
  achievementIconOff: { fontSize: 20, opacity: 0.75 },
  achievementTitle: { fontSize: 13, fontWeight: '700', color: '#222' },
  achievementTitleOff: { fontSize: 13, fontWeight: '700', color: '#8f7e70' },
  achievementDesc: { fontSize: 12, color: '#777', marginTop: 1 },
  emptyAchText: { color: '#8c847d', fontSize: 13, lineHeight: 19 },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 30,
    paddingVertical: 14,
    backgroundColor: '#2f1d14',
    borderWidth: 1,
    borderColor: '#513728',
    marginBottom: 4,
  },
  logoutText: { fontSize: 15, fontWeight: '800', color: '#fff5eb' },
});

export default mas;
