import { StyleSheet } from 'react-native';

import { PREMIUM_ACCENT, PREMIUM_SURFACE_SOFT, THEME, W } from '../constants/theme';

export const profileScreenStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: THEME.border.soft,
  },
  closeBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 18, fontWeight: '700', color: '#111' },
  body: { padding: 24 },
  avatarWrap: { alignItems: 'center', marginBottom: 32, gap: 6 },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: PREMIUM_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImg: { width: 90, height: 90, borderRadius: 45 },
  avatarText: { fontSize: 40, fontWeight: '800', color: '#fff' },
  avatarEmail: { fontSize: 13, color: THEME.text.secondary },
  avatarBadge: {
    position: 'absolute',
    bottom: 52,
    right: W / 2 - 55,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: PREMIUM_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
  },
  avatarHint: { fontSize: 12, color: THEME.text.muted },
  premiumText: { fontSize: 12, color: THEME.text.secondary },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: THEME.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#111',
    marginBottom: 18,
  },
  primaryButton: {
    backgroundColor: THEME.brand.primary,
    borderRadius: 30,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: THEME.brand.primaryBorder,
    shadowColor: THEME.brand.primary,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  primaryButtonText: {
    color: THEME.brand.onPrimary,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.3,
  },
});

export const profilePickStyles = StyleSheet.create({
  trigger: {
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: '#111',
    marginBottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  triggerText: { fontSize: 15, color: '#111' },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '70%' },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: THEME.border.soft,
  },
  sheetTitle: { fontSize: 17, fontWeight: '700', color: '#111' },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: '#f5f5f5',
  },
  itemActive: { backgroundColor: PREMIUM_SURFACE_SOFT },
  itemText: { fontSize: 15, color: '#111' },
});
