import { useAuth } from '../context/AuthContext';
import { FORUM_CATEGORIES } from '../constants/forumCategories';
import { LEVELS, getAchievementDefs, getLevelFromXp } from '../core/gamification';
import { registerForPushNotificationsAsync, scheduleEtioveNotification } from '../core/notifications';
import { formatRelativeTime } from '../core/utils';
import useGamification from '../hooks/useGamification';
import useMainScreenBootstrap from './useMainScreenBootstrap';
import {
  APP_VERSION,
  GOOGLE_PLACES_KEY,
  KEY_FAVS,
  KEY_GAMIFICATION,
  KEY_INTERACTION_FEEDBACK,
  KEY_INTERACTION_FEEDBACK_SETTINGS,
  KEY_NOTIFY_COMMUNITY_SNAPSHOT,
  KEY_NOTIFY_FAVORITES_SNAPSHOT,
  KEY_NOTIFY_FORUM_SNAPSHOT,
  KEY_OFFERS_CACHE,
  KEY_ONBOARDING_DONE,
  KEY_PREFS,
  KEY_PROFILE,
  KEY_VOTES,
  OFFERS_CACHE_TTL_MS,
  PREMIUM_ACCENT,
  PREMIUM_ACCENT_DEEP,
  THEME,
} from './mainScreenConfig';
import useMainScreenDomain from './useMainScreenDomain';
import useMainScreenEffects from './useMainScreenEffects';
import useMainScreenForum from './useMainScreenForum';
import useMainScreenProfileSummary from './useMainScreenProfileSummary';
import useMainScreenTabProps from './useMainScreenTabProps';
import useMainScreenUiState from './useMainScreenUiState';

const BOOTSTRAP_KEYS = {
  favs: KEY_FAVS,
  votes: KEY_VOTES,
  profile: KEY_PROFILE,
  offersCache: KEY_OFFERS_CACHE,
  onboardingDone: KEY_ONBOARDING_DONE,
  feedbackEnabled: KEY_INTERACTION_FEEDBACK,
  feedbackSettings: KEY_INTERACTION_FEEDBACK_SETTINGS,
  notifyCommunitySnapshot: KEY_NOTIFY_COMMUNITY_SNAPSHOT,
  notifyForumSnapshot: KEY_NOTIFY_FORUM_SNAPSHOT,
  notifyFavoritesSnapshot: KEY_NOTIFY_FAVORITES_SNAPSHOT,
};

export default function useMainScreenComposition({ onLogout, services, ui }) {
  const { user } = useAuth();
  const {
    addDocument,
    deleteDocument,
    getCollection,
    getDocument,
    getUserCafes,
    queryCollection,
    restoreAuthTokenFromSecureStore,
    setDocument,
    updateDocument,
    uploadImageToStorage,
  } = services;
  const {
    CardHorizontal,
    CardVertical,
    DiarioCatasSection,
    PackshotImage,
    PremiumBadge,
    SearchInput,
    styles,
  } = ui;

  const screenUi = useMainScreenUiState({
    keyProfile: KEY_PROFILE,
  });

  const gamification = useGamification({ storageKey: KEY_GAMIFICATION });

  const domain = useMainScreenDomain({
    user,
    perfil: screenUi.perfil,
    favs: screenUi.favs,
    setFavs: screenUi.setFavs,
    setCafeDetalle: screenUi.setCafeDetalle,
    registrarEventoGamificacion: gamification.registrarEventoGamificacion,
    busquedaMis: screenUi.busquedaMis,
    busquedaTop: screenUi.busquedaTop,
    googlePlacesKey: GOOGLE_PLACES_KEY,
    offersCacheTtlMs: OFFERS_CACHE_TTL_MS,
    keyFavs: KEY_FAVS,
    keyOffersCache: KEY_OFFERS_CACHE,
    getUserCafes,
    getCollection,
    deleteDocument,
    addDocument,
    queryCollection,
    uploadImageToStorage,
    getDocument,
    setDocument,
    setBuscandoOfertaId: screenUi.setBuscandoOfertaId,
    setErrorOfertas: screenUi.setErrorOfertas,
    ofertasPorCafe: screenUi.ofertasPorCafe,
    setOfertasPorCafe: screenUi.setOfertasPorCafe,
    setOpenOfferCafeId: screenUi.setOpenOfferCafeId,
    setActiveTab: screenUi.setActiveTab,
    showDialog: screenUi.showDialog,
  });

  const profileSummary = useMainScreenProfileSummary({
    user,
    perfil: screenUi.perfil,
    gamification: gamification.gamification,
    brandCardAnim: screenUi.brandCardAnim,
    brandProgressAnim: screenUi.brandProgressAnim,
    setDocument,
  });

  const forum = useMainScreenForum({
    user,
    voteWeight: profileSummary.voteWeight,
    forumThreadScrollRef: screenUi.forumThreadScrollRef,
    forumReplyInputRef: screenUi.forumReplyInputRef,
    forumAuthorName: profileSummary.forumAuthorName,
    currentLevel: profileSummary.currentLevel,
    premium: domain.premium,
    getCollection,
    addDocument,
    updateDocument,
    deleteDocument,
    uploadImageToStorage,
    showDialog: screenUi.showDialog,
  });

  const bootstrap = useMainScreenBootstrap({
    user,
    perfil: screenUi.perfil,
    favs: screenUi.favs,
    allCafes: domain.allCafes,
    forumThreads: forum.forumThreads,
    setFavs: screenUi.setFavs,
    setVotes: screenUi.setVotes,
    setPerfil: screenUi.setPerfil,
    setOfertasPorCafe: screenUi.setOfertasPorCafe,
    setDocument,
    getDocument,
    scheduleEtioveNotification,
    registerForPushNotificationsAsync,
    setActiveTab: screenUi.setActiveTab,
    communityNotificationBootRef: screenUi.communityNotificationBootRef,
    forumNotificationBootRef: screenUi.forumNotificationBootRef,
    favoriteNotificationBootRef: screenUi.favoriteNotificationBootRef,
    appVersion: APP_VERSION,
    keys: BOOTSTRAP_KEYS,
    offersCacheTtlMs: OFFERS_CACHE_TTL_MS,
    showDialog: screenUi.showDialog,
  });

  useMainScreenEffects({
    brandCardAnim: screenUi.brandCardAnim,
    brandProgressAnim: screenUi.brandProgressAnim,
    levelProgress: profileSummary.levelProgress,
    userId: user?.uid,
    restoreAuthTokenFromSecureStore,
    cargarCatas: domain.cargarCatas,
    activeTab: screenUi.activeTab,
    forumThreadsLength: forum.forumThreads.length,
    forumLoading: forum.forumLoading,
    cargarForo: forum.cargarForo,
  });

  const tabProps = useMainScreenTabProps({
    s: styles,
    theme: THEME,
    premiumAccent: PREMIUM_ACCENT,
    premiumAccentDeep: PREMIUM_ACCENT_DEEP,
    keyFavs: KEY_FAVS,
    keyPrefs: KEY_PREFS,
    keyVotes: KEY_VOTES,
    activeTab: screenUi.activeTab,
    setActiveTab: screenUi.setActiveTab,
    setScanning: screenUi.setScanning,
    setShowProfile: screenUi.setShowProfile,
    setCafeDetalle: screenUi.setCafeDetalle,
    perfil: screenUi.perfil,
    profileInitial: profileSummary.profileInitial,
    profileAlias: profileSummary.profileAlias,
    profileName: profileSummary.profileName,
    memberStatus: profileSummary.memberStatus,
    unlockedCount: profileSummary.unlockedCount,
    achievementTotal: profileSummary.achievementTotal,
    pendingAchievements: profileSummary.pendingAchievements,
    achievementProgress: profileSummary.achievementProgress,
    unlockedAchievements: profileSummary.unlockedAchievements,
    newsletterState: bootstrap.newsletterState,
    guardarNewsletter: bootstrap.guardarNewsletter,
    newsletterLoading: bootstrap.newsletterLoading,
    newsletterSaving: bootstrap.newsletterSaving,
    newsletterHasEmail: profileSummary.newsletterHasEmail,
    newsletterEmail: profileSummary.newsletterEmail,
    onLogout,
    appVersion: APP_VERSION,
    iconFaint: THEME.icon.faint,
    interactionFeedbackSettings: bootstrap.interactionFeedbackSettings,
    guardarFeedbackInteracciones: bootstrap.guardarFeedbackInteracciones,
    guardarModoFeedbackInteracciones: bootstrap.guardarModoFeedbackInteracciones,
    premium: domain.premium,
    gamification: gamification.gamification,
    currentLevel: profileSummary.currentLevel,
    nextLevel: profileSummary.nextLevel,
    brandCardAnim: screenUi.brandCardAnim,
    brandCardTranslateY: profileSummary.brandCardTranslateY,
    brandCardScale: profileSummary.brandCardScale,
    brandProgressWidth: profileSummary.brandProgressWidth,
    busqueda: screenUi.busqueda,
    setBusqueda: screenUi.setBusqueda,
    busquedaMis: screenUi.busquedaMis,
    setBusquedaMis: screenUi.setBusquedaMis,
    cargando: domain.cargando,
    cargandoCafInicio: domain.cargandoCafInicio,
    errorCafInicio: domain.errorCafInicio,
    cafeteriasInicio: domain.cafeteriasInicio,
    cargarCafeteriasInicio: domain.cargarCafeteriasInicio,
    allCafes: domain.allCafes,
    filtrar: domain.filtrar,
    favs: screenUi.favs,
    toggleFav: domain.toggleFav,
    ultimosGlobal: domain.ultimosGlobal,
    topCafesVista: domain.topCafesVista,
    flag: profileSummary.flag,
    cafesParaOfertas: domain.cafesParaOfertas,
    abrirOfertasCafe: domain.abrirOfertasCafe,
    abrirOfertaWeb: domain.abrirOfertaWeb,
    ofertasPorCafe: screenUi.ofertasPorCafe,
    buscandoOfertaId: screenUi.buscandoOfertaId,
    openOfferCafeId: screenUi.openOfferCafeId,
    errorOfertas: screenUi.errorOfertas,
    favCafes: domain.favCafes,
    misCafes: domain.misCafes,
    cafesFiltrados: domain.cafesFiltrados,
    eliminarCafe: domain.eliminarCafe,
    notebook: domain.notebook,
    abrirNuevaCata: domain.abrirNuevaCata,
    ultimos100: domain.ultimos100,
    top100: domain.top100,
    forumCategories: FORUM_CATEGORIES,
    forumCategory: forum.forumCategory,
    setForumCategory: forum.setForumCategory,
    forumThread: forum.forumThread,
    setForumThread: forum.setForumThread,
    forumCreateOpen: forum.forumCreateOpen,
    setForumCreateOpen: forum.setForumCreateOpen,
    forumSort: forum.forumSort,
    setForumSort: forum.setForumSort,
    forumLoading: forum.forumLoading,
    forumThreadsByCategory: forum.forumThreadsByCategory,
    forumError: forum.forumError,
    formatRelativeTime,
    forumThreadScrollRef: screenUi.forumThreadScrollRef,
    hasUserVotedForoItem: forum.hasUserVotedForoItem,
    hasUserReportedForoItem: forum.hasUserReportedForoItem,
    isForumOwner: forum.isForumOwner,
    abrirMenuAutorForo: forum.abrirMenuAutorForo,
    votarEnForo: forum.votarEnForo,
    reportarForo: forum.reportarForo,
    forumTopReplies: forum.forumTopReplies,
    forumRepliesByThread: forum.forumRepliesByThread,
    prepararRespuestaForo: forum.prepararRespuestaForo,
    setForumReplyTo: forum.setForumReplyTo,
    forumReplyTo: forum.forumReplyTo,
    forumReplyInputRef: screenUi.forumReplyInputRef,
    forumReplyText: forum.forumReplyText,
    setForumReplyText: forum.setForumReplyText,
    enviarRespuestaForo: forum.enviarRespuestaForo,
    forumSendingReply: forum.forumSendingReply,
    forumTitle: forum.forumTitle,
    setForumTitle: forum.setForumTitle,
    forumBody: forum.forumBody,
    setForumBody: forum.setForumBody,
    forumAccessLevel: forum.forumAccessLevel,
    setForumAccessLevel: forum.setForumAccessLevel,
    forumPhoto: forum.forumPhoto,
    seleccionarFotoForo: forum.seleccionarFotoForo,
    crearHiloForo: forum.crearHiloForo,
    forumSaving: forum.forumSaving,
    forumEditOpen: forum.forumEditOpen,
    setForumEditOpen: forum.setForumEditOpen,
    forumEditCollection: forum.forumEditCollection,
    forumEditTitle: forum.forumEditTitle,
    setForumEditTitle: forum.setForumEditTitle,
    forumEditTarget: forum.forumEditTarget,
    setForumEditTarget: forum.setForumEditTarget,
    forumEditBody: forum.forumEditBody,
    setForumEditBody: forum.setForumEditBody,
    guardarEdicionForo: forum.guardarEdicionForo,
    forumEditing: forum.forumEditing,
    getUserLevel: getLevelFromXp,
    getAchievementDefs,
    levels: LEVELS,
    SearchInput,
    CardVertical,
    CardHorizontal,
    PackshotImage,
    PremiumBadge,
    DiarioCatasSection,
    onGamifyEvent: gamification.registrarEventoGamificacion,
  });

  return {
    user,
    ui: screenUi,
    domain,
    forum,
    bootstrap,
    gamification,
    profileSummary,
    tabProps,
  };
}
