import { Platform, StyleSheet } from 'react-native';

export function createAppStyles({
  H,
  PREMIUM_ACCENT,
  PREMIUM_ACCENT_DEEP,
  PREMIUM_BORDER_SOFT,
  PREMIUM_SURFACE_SOFT,
  PREMIUM_SURFACE_TINT,
  THEME,
  W,
}) {
  const s = StyleSheet.create({
    screen:           { flex: 1, backgroundColor: '#fff' },
    welcomeScreen:    { flex: 1, backgroundColor: '#f6efe7', alignItems: 'center', justifyContent: 'center', padding: 24 },
    welcomeAuraOne:   { position: 'absolute', top: 90, right: -20, width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(119, 82, 57, 0.08)' },
    welcomeAuraTwo:   { position: 'absolute', bottom: 80, left: -40, width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255, 248, 241, 0.76)' },
    welcomeCard:      { width: '100%', borderRadius: 30, backgroundColor: '#fffaf5', borderWidth: 1, borderColor: '#eadbce', paddingVertical: 34, paddingHorizontal: 22, alignItems: 'center', shadowColor: '#3a2416', shadowOpacity: 0.12, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
    welcomeTypeBox:   { width: '100%', alignItems: 'center', justifyContent: 'center', minHeight: 130, gap: 6 },
    welcomeLineTop:   { fontSize: 24, fontWeight: '900', letterSpacing: 4.1, color: '#5e4332' },
    welcomeLineBottom:{ fontSize: 44, fontWeight: '900', letterSpacing: 5.8, color: '#1c120d' },
    welcomeTitle:     { fontSize: 44, fontWeight: '900', letterSpacing: 5.8, color: '#1c120d' },
    welcomeSub:       { fontSize: 10, color: '#6f5444', fontWeight: '800', letterSpacing: 2.1, textAlign: 'center', marginTop: 2 },
    welcomeCaption:   { marginTop: 18, fontSize: 13, color: '#8a6d5b', fontWeight: '600', letterSpacing: 0.4, textAlign: 'center' },
    permScreen:       { flex: 1, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', padding: 32, gap: 16 },
    permTitle:        { fontSize: 22, fontWeight: '700', color: '#111', textAlign: 'center' },
    permSub:          { fontSize: 15, color: THEME.text.secondary, textAlign: 'center' },
    authScroll:       { padding: 24, paddingTop: 36, paddingBottom: 40, flexGrow: 1, justifyContent: 'center', backgroundColor: '#f6efe7' },
    authShell:        { position: 'relative', gap: 22 },
    authAuraOne:      { position: 'absolute', top: -28, right: -18, width: 150, height: 150, borderRadius: 75, backgroundColor: 'rgba(119, 82, 57, 0.09)' },
    authAuraTwo:      { position: 'absolute', bottom: 90, left: -36, width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(255, 248, 241, 0.72)' },
    authBrandBlock:   { paddingTop: 8, paddingBottom: 2 },
    authTitle:        { fontSize: 30, fontWeight: '800', color: '#1f140f', marginBottom: 8 },
    authSub:          { fontSize: 15, color: '#7e6b5f', marginBottom: 24, lineHeight: 22 },
    authKicker:       { fontSize: 11, fontWeight: '800', color: '#8d6d58', textTransform: 'uppercase', letterSpacing: 1.4, marginBottom: 10 },
    authCard:         { backgroundColor: '#fffaf5', borderRadius: 28, padding: 22, borderWidth: 1, borderColor: '#eadbce', shadowColor: '#3a2416', shadowOpacity: 0.1, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 4 },
    authLinks:        { marginTop: 20, gap: 12, alignItems: 'center' },
    authLink:         { color: THEME.brand.accentDeep, fontSize: 14, fontWeight: '700' },
    authLinkMuted:    { color: '#8f837a', fontSize: 14, fontWeight: '600' },
    rememberRow:      { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
    rememberText:     { fontSize: 14, color: THEME.text.tertiary },
    authRememberText: { color: '#5f534b' },
    faceIdBtn:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 16, padding: 14, borderWidth: 1.5, borderColor: THEME.brand.accentDeep, borderRadius: 30, backgroundColor: '#f9f2ea' },
    faceIdText:       { color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
    authLabel:        { color: '#836e61' },
    authInput:        { backgroundColor: '#f8f1ea', borderWidth: 1, borderColor: '#e8dacd', color: '#221610' },
    authPrimaryBtn:   { backgroundColor: THEME.brand.primary, borderRadius: 30, padding: 16, alignItems: 'center', marginTop: 8, shadowColor: THEME.brand.primary, shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
    authPrimaryBtnText:{ color: THEME.brand.onPrimary, fontWeight: '800', fontSize: 15, letterSpacing: 0.3 },
    authSecondaryBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 14, padding: 14, borderWidth: 1.2, borderColor: '#dcc8b7', borderRadius: 30, backgroundColor: '#f9f2ea' },
    authSecondaryBtnText:{ color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
    topBar:           { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 8, gap: 10 },
    homeBrandWrap:    { alignItems: 'center', justifyContent: 'center', gap: 5, paddingTop: 2, paddingBottom: 2 },
    homeWordmark:     { fontSize: 42, fontWeight: '900', letterSpacing: 4.2, color: '#1c120d', textShadowColor: 'rgba(111, 84, 68, 0.08)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 8, fontFamily: 'PlayfairDisplay_800ExtraBold' },
    homeLoverRow:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
    homeLoverText:    { fontSize: 10, fontWeight: '800', color: '#6f5444', letterSpacing: 2.2 },
    homeMiniSealOuter:{ width: 24, height: 24, borderRadius: 12, borderWidth: 1, borderColor: '#c4a18a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fcf7f1' },
    homeMiniSealMiddle:{ width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: 'rgba(154, 121, 99, 0.4)', alignItems: 'center', justifyContent: 'center' },
    homeMiniSealInner:{ width: 12, height: 12, borderRadius: 6, borderWidth: 1, borderColor: '#8f6a53', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f2e7dc' },
    homeMiniSealText: { fontSize: 8, fontWeight: '900', color: '#6f5444', letterSpacing: 0.5 },
    wordmarkWrap:     { alignItems: 'center', justifyContent: 'center', gap: 4, paddingHorizontal: 2, paddingTop: 4 },
    wordmarkCrest:    { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 3 },
    wordmarkMiniLabelWrap:{ minWidth: 78, alignItems: 'center' },
    wordmarkMiniLabel:{ fontSize: 9, fontWeight: '800', color: '#9a7963', letterSpacing: 2.2 },
    wordmarkSealOuter:{ width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderColor: '#c4a18a', alignItems: 'center', justifyContent: 'center', backgroundColor: '#fcf7f1' },
    wordmarkSealMiddle:{ width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: 'rgba(154, 121, 99, 0.38)', alignItems: 'center', justifyContent: 'center' },
    wordmarkSeal:     { width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: '#8f6a53', alignItems: 'center', justifyContent: 'center', backgroundColor: '#f2e7dc' },
    wordmarkSealText: { fontSize: 11, fontWeight: '900', color: '#6f5444', letterSpacing: 1.1 },
    wordmark:         { fontSize: 40, fontWeight: '900', letterSpacing: 4.2, color: '#1c120d', textShadowColor: 'rgba(111, 84, 68, 0.08)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 8, fontFamily: 'PlayfairDisplay_800ExtraBold' },
    wordmarkSub:      { fontSize: 10, color: '#8a6b57', fontWeight: '800', letterSpacing: 3.2, marginTop: -2 },
    wordmarkTag:      { fontSize: 10, color: '#6f5444', fontWeight: '800', letterSpacing: 2.1, textAlign: 'center', marginTop: 2 },
    authWordmarkSub:  { marginBottom: 10 },
    authWordmarkTag:  { marginTop: 0 },
    locationPill:     { position: 'relative', overflow: 'hidden', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 10, minWidth: 210, backgroundColor: '#1f140f', borderWidth: 1, borderColor: '#4e3426', shadowColor: '#170d08', shadowOpacity: 0.24, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
    locationText:     { fontSize: 15, fontWeight: '800', color: '#f8ead9', letterSpacing: 0.2 },
    brandPillContent: { gap: 6 },
    brandEyebrow:     { fontSize: 9, fontWeight: '700', color: '#d6b89b', textTransform: 'uppercase', letterSpacing: 1.1 },
    brandRow:         { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
    brandMemberRow:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    brandMemberIdentity: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    brandMemberAvatar:{ width: 40, height: 40, borderRadius: 20, borderWidth: 1.2, borderColor: 'rgba(255, 236, 220, 0.2)' },
    brandMemberAvatarFallback:{ width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 248, 241, 0.1)', borderWidth: 1.2, borderColor: 'rgba(255, 236, 220, 0.14)', alignItems: 'center', justifyContent: 'center' },
    brandMemberAvatarText:{ color: '#fff1e4', fontSize: 15, fontWeight: '800' },
    brandMemberCopy:  { flex: 1, gap: 2 },
    brandAlias:       { fontSize: 14, fontWeight: '800', color: '#fff4ea' },
    brandName:        { fontSize: 10, color: '#d2bead' },
    brandTitleWrap:   { flex: 1, gap: 3 },
    brandLevelBadge:  { backgroundColor: 'rgba(248, 225, 198, 0.12)', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start', borderWidth: 1, borderColor: 'rgba(248, 225, 198, 0.18)' },
    brandLevelText:   { fontSize: 10, fontWeight: '800', color: '#fff4ea' },
    brandXpText:      { fontSize: 11, color: '#d4c1b1', fontWeight: '600' },
    brandMetaRow:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
    brandMetaText:    { fontSize: 10, color: '#c9ab90' },
    brandProgressTrack:{ height: 6, borderRadius: 999, backgroundColor: 'rgba(255, 244, 234, 0.12)', overflow: 'hidden' },
    brandProgressFill:{ height: '100%', borderRadius: 999, backgroundColor: '#d18b4a' },
    brandStatsRow:    { flexDirection: 'row', gap: 6 },
    brandStatCard:    { flex: 1, backgroundColor: 'rgba(255, 248, 241, 0.06)', borderRadius: 12, paddingVertical: 6, paddingHorizontal: 4, borderWidth: 1, borderColor: 'rgba(255, 234, 214, 0.08)', alignItems: 'center' },
    brandStatValue:   { fontSize: 13, fontWeight: '800', color: '#fff1e4' },
    brandStatLabel:   { fontSize: 9, color: '#cfb39a', marginTop: 1 },
    brandDecorOne:    { position: 'absolute', top: -30, right: -20, width: 94, height: 94, borderRadius: 47, backgroundColor: 'rgba(209, 139, 74, 0.13)' },
    brandDecorTwo:    { position: 'absolute', bottom: -48, left: -26, width: 98, height: 98, borderRadius: 49, backgroundColor: 'rgba(255, 244, 234, 0.06)' },
    brandTopRule:     { position: 'absolute', top: 0, left: 14, right: 14, height: 1, backgroundColor: 'rgba(255, 238, 220, 0.18)' },
    profileBtn:       { padding: 2 },
    profileAvatar:    { width: 36, height: 36, borderRadius: 18, backgroundColor: PREMIUM_ACCENT, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
    profileAvatarText:{ color: THEME.text.inverse, fontWeight: '700', fontSize: 16 },
    searchWrap:       { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, marginVertical: 10, backgroundColor: '#f5f5f5', borderRadius: 25, paddingHorizontal: 14, height: 44 },
    searchInput:      { flex: 1, fontSize: 15, color: '#222', marginLeft: 8 },
    sectionHeader:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, marginTop: 20, marginBottom: 2 },
    sectionTitle:     { fontSize: 20, fontWeight: '700', color: '#111', fontFamily: 'PlayfairDisplay_700Bold' },
    sectionSub:       { fontSize: 13, color: THEME.text.secondary, paddingHorizontal: 16, marginBottom: 14 },
    pageTitle:        { fontSize: 24, fontWeight: '700', color: '#111', marginBottom: 12, fontFamily: 'PlayfairDisplay_700Bold' },
    empty:            { color: THEME.text.muted, textAlign: 'center', marginTop: 40, fontSize: 14 },
    packshotFrame:    { backgroundColor: '#ffffff', borderRadius: 18, borderWidth: 1, borderColor: '#f1ece4', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2, alignItems: 'center', justifyContent: 'center' },
    packshotInner:    { width: '100%', height: '100%', backgroundColor: '#fff', borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
    packshotImage:    { width: '84%', height: '84%' },
    packshotHeroFrame:{ width: '68%', height: '72%', borderRadius: 28, padding: 14 },
    packshotHeroImage:{ width: '88%', height: '88%' },
    packshotCardFrame:{ width: 132, height: 172, marginTop: 14, borderRadius: 18, padding: 10 },
    packshotCardImage:{ width: '86%', height: '86%' },
    packshotListFrame:{ width: 68, height: 88, borderRadius: 14, padding: 8 },
    packshotListImage:{ width: '88%', height: '88%' },
    cardH:            { width: 160, marginRight: 4 },
    cardHImg:         { width: 160, height: 200, borderRadius: 10, backgroundColor: '#f8f7f4', alignItems: 'center', justifyContent: 'center', marginBottom: 8, overflow: 'hidden' },
    cardHOrigin:      { fontSize: 12, color: THEME.text.secondary, marginBottom: 2 },
    cardHName:        { fontSize: 14, fontWeight: '700', color: '#111', lineHeight: 19 },
    cardHRating:      { fontSize: 13, fontWeight: '600', color: PREMIUM_ACCENT },
    cardHVotos:       { fontSize: 12, color: THEME.text.secondary },
    cardV:            { flexDirection: 'row', gap: 12, alignItems: 'flex-start', marginBottom: 16, paddingBottom: 16, borderBottomWidth: 0.5, borderBottomColor: THEME.border.soft },
    cardVImg:         { width: 80, height: 100, borderRadius: 10, backgroundColor: '#f8f7f4', alignItems: 'center', justifyContent: 'center', flexShrink: 0, overflow: 'hidden' },
    cardVOrigin:      { fontSize: 12, color: THEME.text.secondary, marginBottom: 2 },
    cardVName:        { fontSize: 15, fontWeight: '700', color: THEME.text.primary, marginBottom: 5 },
    cardVNotas:       { fontSize: 12, color: THEME.text.muted, marginTop: 5, lineHeight: 17 },
    offerHint:        { fontSize: 12, color: '#666', marginTop: 8 },
    offerMetaRow:     { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 3 },
    offerSourceBadge: { fontSize: 10, fontWeight: '800', color: '#fff', backgroundColor: '#111', borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3 },
    badgeRed:         { position: 'absolute', top: 8, left: 8, backgroundColor: PREMIUM_ACCENT, borderRadius: 12, paddingHorizontal: 7, paddingVertical: 3 },
    badgeText:        { color: '#fff', fontSize: 11, fontWeight: '700' },
    rankRow:          { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 0.5, borderBottomColor: THEME.border.soft },
    rankNum:          { fontSize: 22, fontWeight: '700', color: '#ccc', width: 28 },
    rankName:         { fontSize: 15, fontWeight: '600', color: '#111' },
    rankVotos:        { fontSize: 12, color: THEME.text.secondary, marginTop: 2 },
    redBtn:           { backgroundColor: THEME.brand.primary, borderRadius: 30, padding: 16, alignItems: 'center', marginTop: 8, borderWidth: 1, borderColor: THEME.brand.primaryBorder, shadowColor: THEME.brand.primary, shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
    redBtnText:       { color: THEME.brand.onPrimary, fontWeight: '800', fontSize: 15, letterSpacing: 0.3 },
    bottomBar:        { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: THEME.surface.base, borderTopWidth: 0.5, borderTopColor: THEME.border.soft, flexDirection: 'row', alignItems: 'center', paddingBottom: 20, paddingTop: 10 },
    tabBtn:           { flex: 1, alignItems: 'center', gap: 3 },
    tabLabel:         { fontSize: 10, color: THEME.text.secondary },
    tabBadge:         { position: 'absolute', top: -4, right: -8, width: 16, height: 16, borderRadius: 8, backgroundColor: THEME.brand.accent, alignItems: 'center', justifyContent: 'center' },
    tabBadgeText:     { color: THEME.text.inverse, fontSize: 9, fontWeight: '700' },
    camBtn:           { width: 60, height: 60, borderRadius: 30, backgroundColor: THEME.brand.primary, borderWidth: 1.5, borderColor: THEME.brand.primaryBorderStrong, alignItems: 'center', justifyContent: 'center', marginTop: -20, shadowColor: THEME.brand.primary, shadowOpacity: 0.34, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
    formScroll:       { padding: 20, paddingTop: 52, paddingBottom: 50 },
    backRow:          { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 20 },
    backText:         { color: PREMIUM_ACCENT_DEEP, fontSize: 15 },
    formTitle:        { fontSize: 26, fontWeight: '700', color: '#111', marginBottom: 20 },
    fotoEmpty:        { backgroundColor: '#f5f5f5', borderRadius: 14, height: 140, alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 20 },
    fotoEmptyText:    { color: THEME.text.muted, fontSize: 14 },
    fotoFull:         { width: '100%', height: 200, borderRadius: 14, marginBottom: 8 },
    retake:           { color: PREMIUM_ACCENT_DEEP, fontSize: 13, textAlign: 'right', marginBottom: 20 },
    label:            { fontSize: 12, fontWeight: '600', color: THEME.text.secondary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 8 },
    input:            { backgroundColor: '#f5f5f5', borderRadius: 12, padding: 14, fontSize: 15, color: '#111', marginBottom: 18 },
    communityScrollContent: { paddingBottom: 126 },
    communityIntroWrap: { paddingHorizontal: 16, paddingTop: 18 },
    communityHeroCard:  { position: 'relative', overflow: 'hidden', borderRadius: 22, backgroundColor: '#1f140f', borderWidth: 1, borderColor: '#4c3123', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 14, marginBottom: 14, shadowColor: '#170d08', shadowOpacity: 0.26, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
    communityHeroGlowOne: { position: 'absolute', width: 148, height: 148, borderRadius: 74, right: -40, top: -52, backgroundColor: 'rgba(209, 139, 74, 0.24)' },
    communityHeroGlowTwo: { position: 'absolute', width: 120, height: 120, borderRadius: 60, left: -24, bottom: -40, backgroundColor: 'rgba(255, 233, 210, 0.08)' },
    communityHeroKicker: { color: '#cfad92', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
    communityHeroTitle: { color: '#fff6ec', fontSize: 24, fontWeight: '900', marginTop: 6 },
    communityHeroSub: { color: '#dcc4af', fontSize: 12, lineHeight: 18, marginTop: 6, paddingRight: 32 },
    communityHeroMetaRow: { marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    communityHeroBadge: { borderRadius: 999, borderWidth: 1, borderColor: 'rgba(255, 233, 210, 0.34)', backgroundColor: 'rgba(255, 248, 241, 0.09)', paddingHorizontal: 10, paddingVertical: 6 },
    communityHeroBadgeText: { color: '#fff3e8', fontSize: 11, fontWeight: '800' },
    communityHeroHint: { color: '#cab29f', fontSize: 11, fontWeight: '600' },
    communityCategoryGrid: { paddingHorizontal: 16, gap: 10 },
    forumCatCard:     { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#fffaf6', borderRadius: 16, borderWidth: 1, borderColor: '#e7d5c5', padding: 14, shadowColor: '#2f1d14', shadowOpacity: 0.08, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 2 },
    forumCatEmoji:    { fontSize: 24 },
    forumCatTitle:    { fontSize: 15, fontWeight: '800', color: '#2d1d13' },
    forumCatDesc:     { fontSize: 12, color: '#7d6a5f', marginTop: 2, lineHeight: 17 },
    forumCatChevronWrap: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: '#e2cebc', backgroundColor: '#f5eade', alignItems: 'center', justifyContent: 'center' },
    forumHeaderRow:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 10 },
    forumNewBtn:      { backgroundColor: THEME.brand.primary, borderRadius: 999, paddingHorizontal: 15, paddingVertical: 8, borderWidth: 1, borderColor: '#5b3c2a', shadowColor: '#2f1d14', shadowOpacity: 0.16, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
    forumNewBtnText:  { color: THEME.brand.onPrimary, fontWeight: '800', fontSize: 12, letterSpacing: 0.3 },
    forumSortRow:     { flexDirection: 'row', gap: 8, marginTop: 8 },
    forumSortChip:    { borderRadius: 999, borderWidth: 1, borderColor: '#dbc5b3', paddingHorizontal: 12, paddingVertical: 7, backgroundColor: '#fffaf5' },
    forumSortChipActive:{ backgroundColor: '#2f1d14', borderColor: '#2f1d14' },
    forumSortText:    { fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '700' },
    forumSortTextActive:{ color: '#fff' },
    forumSkeletonWrap: { paddingHorizontal: 16, paddingTop: 4, gap: 10 },
    forumSkeletonCard: { position: 'relative', overflow: 'hidden', backgroundColor: '#f4e9dd', borderRadius: 16, borderWidth: 1, borderColor: '#e7d3c2', padding: 12 },
    forumSkeletonLineLg: { height: 14, width: '78%', borderRadius: 8, backgroundColor: '#e5d2bf', marginBottom: 8 },
    forumSkeletonLineMd: { height: 12, width: '96%', borderRadius: 7, backgroundColor: '#eadbcf', marginBottom: 6 },
    forumSkeletonLineSm: { height: 12, width: '72%', borderRadius: 7, backgroundColor: '#eadbcf', marginBottom: 10 },
    forumSkeletonMeta: { flexDirection: 'row', gap: 8 },
    forumSkeletonPill: { height: 22, width: 56, borderRadius: 11, backgroundColor: '#e3cfbc' },
    forumSkeletonShimmer: { position: 'absolute', top: 0, bottom: 0, width: 130, backgroundColor: 'rgba(255,255,255,0.22)' },
    forumThreadCard:  { backgroundColor: '#fffaf6', borderRadius: 16, borderWidth: 1, borderColor: '#e8d7c8', padding: 12, shadowColor: '#2f1d14', shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
    forumThreadTitle: { fontSize: 15, fontWeight: '800', color: THEME.text.primary, marginBottom: 4 },
    forumThreadBody:  { fontSize: 13, color: '#4a3f36', lineHeight: 20 },
    forumMetaRow:     { marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    forumAuthorRow:   { flexDirection: 'row', alignItems: 'center', gap: 8 },
    forumAvatar:      { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#e9ddcf' },
    forumAvatarText:  { fontSize: 12, fontWeight: '800', color: THEME.brand.accentDeep },
    forumAuthorName:  { fontSize: 12, fontWeight: '700', color: THEME.text.primary },
    forumAuthorLevel: { fontSize: 10, color: THEME.brand.accentDeep, fontWeight: '700' },
    forumMetaText:    { fontSize: 11, color: '#8c786b' },
    forumCountersRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 8 },
    forumCounter:     { fontSize: 12, color: '#7a675a', fontWeight: '700' },
    forumMainPost:    { marginTop: 4, backgroundColor: '#fff8f1', borderRadius: 16, borderWidth: 1, borderColor: '#e5d2c1', padding: 14, shadowColor: '#2f1d14', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 2 },
    forumMainPostHead:{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
    forumMainPostImage:{ marginTop: 8, width: '100%', height: 160, borderRadius: 10 },
    forumReplyCard:   { marginBottom: 10, backgroundColor: '#fffaf6', borderRadius: 12, borderWidth: 1, borderColor: '#ecdfd3', padding: 10 },
    forumChildReplyCard:{ marginTop: 8, marginLeft: 14, backgroundColor: '#f8efe6', borderRadius: 10, borderWidth: 1, borderColor: '#ebdccf', padding: 9 },
    forumActionBtn:   { backgroundColor: '#f5e8db', borderWidth: 1, borderColor: '#ddc6b1', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
    forumActionText:  { fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '800' },
    forumActionBtnDisabled:{ backgroundColor: '#f3f0eb', borderColor: '#e3ddd6' },
    forumActionTextDisabled:{ color: '#a39a90' },
    forumMetaActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    forumDotsBtn:     { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#f4e6d8', borderWidth: 1, borderColor: '#dcc4ae' },
    forumComposerWrap:{ borderTopWidth: 1, borderTopColor: '#e8ddd2', backgroundColor: '#fff', paddingHorizontal: 12, paddingTop: 10, paddingBottom: Platform.OS === 'ios' ? 34 : 86 },
    forumReplyingTag: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f5ece2', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7, marginBottom: 8 },
    forumReplyingText:{ fontSize: 12, color: THEME.brand.accentDeep, fontWeight: '600' },
    forumComposerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
    forumComposerInput:{ flex: 1, minHeight: 42, maxHeight: 110, backgroundColor: '#f5f0e9', borderRadius: 12, borderWidth: 1, borderColor: '#e3d8cc', paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: '#2a1d14' },
    forumSendBtn:     { width: 42, height: 42, borderRadius: 21, backgroundColor: THEME.brand.primary, alignItems: 'center', justifyContent: 'center' },
    forumModalOverlay:{ flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
    forumModalCard:   { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 18, borderWidth: 1, borderColor: '#ebdfd3' },
    forumCountText:   { fontSize: 12, color: THEME.text.secondary, textAlign: 'right', marginTop: -8, marginBottom: 10 },
  });

  const srch = StyleSheet.create({
    dropdown:  { position: 'absolute', top: 54, left: 16, right: 16, backgroundColor: '#fff', borderRadius: 12, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 5, zIndex: 200 },
    suggItem:  { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: '#f5f5f5' },
    suggText:  { fontSize: 14, color: '#333', flex: 1 },
  });

  const q = StyleSheet.create({
    introBox:          { margin: 16, backgroundColor: PREMIUM_SURFACE_SOFT, borderRadius: 20, padding: 24, alignItems: 'center', gap: 10 },
    introEmoji:        { fontSize: 40 },
    introTitle:        { fontSize: 22, fontWeight: '800', color: '#111', textAlign: 'center' },
    introSub:          { fontSize: 14, color: '#666', textAlign: 'center', lineHeight: 20 },
    startBtn:          { backgroundColor: PREMIUM_ACCENT_DEEP, borderRadius: 30, paddingHorizontal: 32, paddingVertical: 14, marginTop: 8 },
    startBtnText:      { color: '#fff', fontWeight: '700', fontSize: 16 },
    quizBox:           { margin: 16, backgroundColor: '#fff', borderRadius: 20, padding: 20, gap: 16, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 4 }, elevation: 3 },
    progressRow:       { flexDirection: 'row', gap: 6, justifyContent: 'center' },
    progressDot:       { width: 8, height: 8, borderRadius: 4, backgroundColor: THEME.border.soft },
    progressDotActive: { backgroundColor: PREMIUM_ACCENT, width: 24 },
    quizEmoji:         { fontSize: 36, textAlign: 'center' },
    quizPregunta:      { fontSize: 20, fontWeight: '700', color: '#111', textAlign: 'center' },
    opcionesGrid:      { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center' },
    opcion:            { width: (W - 80) / 2, backgroundColor: '#f9f9f9', borderRadius: 16, padding: 14, alignItems: 'center', gap: 4, borderWidth: 1.5, borderColor: '#f0f0f0' },
    opcionIcon:        { fontSize: 28 },
    opcionLabel:       { fontSize: 15, fontWeight: '700', color: '#111' },
    opcionDesc:        { fontSize: 11, color: THEME.text.secondary, textAlign: 'center' },
    resultsHeader:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, marginBottom: 12, marginTop: 16 },
    resultsTitle:      { fontSize: 20, fontWeight: '700', color: '#111' },
    resultsSub:        { fontSize: 13, color: THEME.text.secondary },
    resetBtn:          { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: PREMIUM_SURFACE_SOFT, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6 },
    resetText:         { color: PREMIUM_ACCENT_DEEP, fontSize: 13, fontWeight: '600' },
    favBtnCard:        { position: 'absolute', top: 6, right: 6, width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center' },
  });

  const det = StyleSheet.create({
    hero:         { width: W, height: H * 0.42, backgroundColor: '#f5f0eb' },
    heroGrad:     { position: 'absolute', bottom: 0, left: 0, right: 0, height: 120, backgroundColor: 'rgba(0,0,0,0.45)' },
    backBtn:      { position: 'absolute', top: 52, left: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center' },
    favBtn:       { position: 'absolute', top: 52, right: 64, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center' },
    deleteBtn:    { position: 'absolute', top: 52, right: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(220,50,50,0.7)', alignItems: 'center', justifyContent: 'center' },
    scoreBox:     { position: 'absolute', bottom: 20, left: 20, gap: 4 },
    scoreNum:     { fontSize: 42, fontWeight: '800', color: '#fff' },
    scoreVotos:   { fontSize: 13, color: 'rgba(255,255,255,0.8)' },
    body:         { padding: 20 },
    nombre:       { fontSize: 26, fontWeight: '800', color: '#111', marginBottom: 4 },
    finca:        { fontSize: 15, color: '#555', marginBottom: 4 },
    originRow:    { marginBottom: 14 },
    originText:   { fontSize: 14, color: THEME.text.secondary },
    chipsWrap:    { marginBottom: 20 },
    chip:         { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: PREMIUM_SURFACE_SOFT, borderWidth: 1, borderColor: PREMIUM_BORDER_SOFT, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6, marginRight: 8 },
    chipText:     { fontSize: 12, color: PREMIUM_ACCENT_DEEP, fontWeight: '600' },
    votarBox:     { backgroundColor: PREMIUM_SURFACE_TINT, borderRadius: 16, padding: 18, alignItems: 'center', gap: 4, marginBottom: 4 },
    votarTitle:   { fontSize: 17, fontWeight: '700', color: '#111' },
    votarSub:     { fontSize: 13, color: THEME.text.secondary },
    scaBox:       { backgroundColor: '#f9f9f9', borderRadius: 16, padding: 16, marginBottom: 4, gap: 8 },
    scaLeft:      { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
    scaScore:     { fontSize: 36, fontWeight: '800', color: '#111' },
    scaLabel:     { fontSize: 13, color: THEME.text.secondary },
    scaBar:       { height: 8, backgroundColor: THEME.border.soft, borderRadius: 4, overflow: 'hidden' },
    scaFill:      { height: '100%', backgroundColor: PREMIUM_ACCENT, borderRadius: 4 },
    scaCat:       { fontSize: 13, color: '#555', fontWeight: '600' },
    divider:      { height: 0.5, backgroundColor: THEME.border.soft, marginVertical: 20 },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: '#111', marginBottom: 14, fontFamily: 'PlayfairDisplay_700Bold' },
    notasBox:     { backgroundColor: PREMIUM_SURFACE_TINT, borderRadius: 12, padding: 14, marginBottom: 14 },
    notasLabel:   { fontSize: 11, fontWeight: '700', color: PREMIUM_ACCENT_DEEP, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 6 },
    notasText:    { fontSize: 15, color: '#333', lineHeight: 22 },
    sensRow:      { flexDirection: 'row', gap: 10 },
    sensItem:     { flex: 1, backgroundColor: '#f9f9f9', borderRadius: 12, padding: 12, alignItems: 'center', gap: 4 },
    sensLabel:    { fontSize: 11, color: THEME.text.secondary, fontWeight: '600' },
    sensVal:      { fontSize: 12, color: '#333', textAlign: 'center' },
    infoRow:      { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderBottomWidth: 0.5, borderBottomColor: '#f0f0f0' },
    infoLabel:    { fontSize: 14, color: THEME.text.secondary, flex: 1 },
    infoVal:      { fontSize: 14, color: '#111', fontWeight: '500', flex: 2, textAlign: 'right' },
    prepBox:      { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: PREMIUM_SURFACE_TINT, borderRadius: 12, padding: 14 },
    prepText:     { fontSize: 14, color: '#333', flex: 1 },
    certText:     { fontSize: 14, color: '#555', lineHeight: 22 },
    precioBox:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#f9f9f9', borderRadius: 12, padding: 16, marginTop: 20 },
    precioLabel:  { fontSize: 14, color: THEME.text.secondary },
    precioVal:    { fontSize: 20, fontWeight: '800', color: PREMIUM_ACCENT },
  });

  const scan = StyleSheet.create({
    overlay:         { flex: 1 },
    top:             { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' },
    middle:          { flexDirection: 'row', height: W * 0.72 },
    side:            { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' },
    window:          { width: W * 0.72, height: W * 0.72 },
    bottom:          { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', paddingTop: 24, gap: 20 },
    hint:            { color: '#fff', fontSize: 15, textAlign: 'center', paddingHorizontal: 32 },
    tabs:            { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 25, padding: 4 },
    tabActive:       { backgroundColor: '#fff', borderRadius: 22, paddingHorizontal: 20, paddingVertical: 10 },
    tabInactive:     { paddingHorizontal: 20, paddingVertical: 10 },
    tabTextActive:   { color: '#111', fontWeight: '700', fontSize: 14 },
    tabTextInactive: { color: 'rgba(255,255,255,0.7)', fontSize: 14 },
    corner:          { position: 'absolute', width: 24, height: 24, borderColor: PREMIUM_ACCENT, borderWidth: 3 },
    tl:              { top: 0, left: 0, borderBottomWidth: 0, borderRightWidth: 0 },
    tr:              { top: 0, right: 0, borderBottomWidth: 0, borderLeftWidth: 0 },
    bl:              { bottom: 0, left: 0, borderTopWidth: 0, borderRightWidth: 0 },
    br:              { bottom: 0, right: 0, borderTopWidth: 0, borderLeftWidth: 0 },
    scanLine:        { position: 'absolute', top: '50%', left: 0, right: 0, height: 2, backgroundColor: PREMIUM_ACCENT, opacity: 0.8 },
    backBtn:         { position: 'absolute', top: 52, left: 16, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center' },
    galleryBtn:      { position: 'absolute', bottom: 60, left: 40, width: 52, height: 52, borderRadius: 26, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  });

  const prf = StyleSheet.create({
    header:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: THEME.border.soft },
    closeBtn:    { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    title:       { fontSize: 18, fontWeight: '700', color: '#111' },
    body:        { padding: 24 },
    avatarWrap:  { alignItems: 'center', marginBottom: 32, gap: 6 },
    avatar:      { width: 90, height: 90, borderRadius: 45, backgroundColor: PREMIUM_ACCENT, alignItems: 'center', justifyContent: 'center' },
    avatarImg:   { width: 90, height: 90, borderRadius: 45 },
    avatarText:  { fontSize: 40, fontWeight: '800', color: '#fff' },
    avatarEmail: { fontSize: 13, color: THEME.text.secondary },
    avatarBadge: { position: 'absolute', bottom: 52, right: W / 2 - 55, width: 26, height: 26, borderRadius: 13, backgroundColor: PREMIUM_ACCENT, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  });

  const pick = StyleSheet.create({
    trigger:     { backgroundColor: '#f5f5f5', borderRadius: 12, padding: 14, fontSize: 15, color: '#111', marginBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    triggerText: { fontSize: 15, color: '#111' },
    overlay:     { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
    sheet:       { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: H * 0.7 },
    sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 0.5, borderBottomColor: THEME.border.soft },
    sheetTitle:  { fontSize: 17, fontWeight: '700', color: '#111' },
    item:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 0.5, borderBottomColor: '#f5f5f5' },
    itemActive:  { backgroundColor: PREMIUM_SURFACE_SOFT },
    itemText:    { fontSize: 15, color: '#111' },
  });

  const mas = StyleSheet.create({
    premiumCard:  { position: 'relative', overflow: 'hidden', marginTop: 8, marginBottom: 18, backgroundColor: '#1f140f', borderRadius: 20, padding: 16, borderWidth: 1, borderColor: '#4a3022' },
    premiumGlow:  { position: 'absolute', width: 170, height: 170, borderRadius: 85, right: -44, top: -68, backgroundColor: 'rgba(209, 139, 74, 0.2)' },
    premiumGlowTwo:{ position: 'absolute', width: 120, height: 120, borderRadius: 60, left: -30, bottom: -24, backgroundColor: 'rgba(255, 233, 210, 0.08)' },
    clubTag:      { color: '#caa487', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginBottom: 8 },
    premiumTopRow:{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    premiumIdentity:{ flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    premiumAvatar:{ width: 44, height: 44, borderRadius: 22, borderWidth: 1.2, borderColor: 'rgba(255, 232, 212, 0.28)' },
    premiumAvatarFallback:{ width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255, 248, 241, 0.13)', borderWidth: 1.2, borderColor: 'rgba(255, 232, 212, 0.22)' },
    premiumAvatarText:{ color: '#fff3e8', fontSize: 16, fontWeight: '800' },
    premiumAlias: { color: '#fff4ea', fontSize: 14, fontWeight: '800' },
    premiumName:  { color: '#d8c0ad', fontSize: 12, marginTop: 1 },
    premiumLevelBadge:{ borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: 'rgba(250, 229, 206, 0.32)', backgroundColor: 'rgba(255, 248, 241, 0.1)' },
    premiumLevelText:{ color: '#fff4ea', fontSize: 11, fontWeight: '700' },
    premiumExplain:{ color: '#d8c0ad', fontSize: 12, lineHeight: 18, marginTop: 10 },
    premiumStatsRow:{ flexDirection: 'row', gap: 8, marginTop: 14 },
    premiumStatCard:{ flex: 1, borderRadius: 12, backgroundColor: 'rgba(255, 248, 241, 0.08)', borderWidth: 1, borderColor: 'rgba(250, 229, 206, 0.12)', paddingVertical: 8, alignItems: 'center' },
    premiumStatValue:{ color: '#fff4ea', fontSize: 16, fontWeight: '800' },
    premiumStatLabel:{ color: '#d0b8a4', fontSize: 10, marginTop: 2 },
    memberProgressRow:{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14, marginBottom: 8 },
    memberProgressText:{ color: '#edd8c5', fontSize: 11, fontWeight: '700' },
    memberProgressBar:{ height: 8, borderRadius: 999, backgroundColor: 'rgba(255, 248, 241, 0.12)', overflow: 'hidden' },
    memberProgressFill:{ height: '100%', borderRadius: 999, backgroundColor: '#d18b4a' },
    quickGrid:    { flexDirection: 'row', gap: 10, marginBottom: 14 },
    quickCard:    { flex: 1, borderRadius: 16, padding: 14, borderWidth: 1 },
    quickCardDark:{ backgroundColor: '#2a1a12', borderColor: '#4d3222' },
    quickCardSoft:{ backgroundColor: '#f8efe6', borderColor: '#e9d8c7' },
    quickTitleDark:{ marginTop: 8, color: '#fff3e8', fontSize: 14, fontWeight: '800' },
    quickSubDark: { marginTop: 3, color: '#d8bcaa', fontSize: 11 },
    quickTitle:   { marginTop: 8, color: '#2d1d13', fontSize: 14, fontWeight: '800' },
    quickSub:     { marginTop: 3, color: '#7d6a5f', fontSize: 11 },
    blockTitle:   { fontSize: 12, fontWeight: '800', color: '#876a56', textTransform: 'uppercase', letterSpacing: 0.9, marginTop: 4, marginBottom: 8 },
    listCard:     { backgroundColor: '#fffaf6', borderRadius: 16, borderWidth: 1, borderColor: '#eadbce', paddingHorizontal: 14, marginBottom: 16 },
    achievementsCard:{ backgroundColor: '#fffaf6', borderRadius: 16, borderWidth: 1, borderColor: '#eadbce', padding: 12, gap: 8, marginBottom: 14 },
    newsletterCard:{ backgroundColor: '#fffaf6', borderRadius: 18, borderWidth: 1, borderColor: '#eadbce', padding: 14, marginBottom: 14 },
    newsletterTopRow:{ flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
    newsletterTitleWrap:{ flex: 1, paddingRight: 4 },
    newsletterTitle:{ color: '#2c1c14', fontSize: 15, fontWeight: '800' },
    newsletterSub:{ color: '#7d6a5f', fontSize: 12, lineHeight: 18, marginTop: 3 },
    newsletterMetaRow:{ gap: 8, marginTop: 12 },
    newsletterStatusPill:{ alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1 },
    newsletterStatusOn:{ backgroundColor: '#f3e8db', borderColor: '#d6b798' },
    newsletterStatusOff:{ backgroundColor: '#f6f1eb', borderColor: '#e6d8c9' },
    newsletterStatusText:{ fontSize: 11, fontWeight: '800' },
    newsletterStatusTextOn:{ color: '#6b4a37' },
    newsletterStatusTextOff:{ color: '#8d7a6c' },
    newsletterEmail:{ color: '#3a2a20', fontSize: 13, fontWeight: '600' },
    newsletterNote:{ color: '#8c847d', fontSize: 12, lineHeight: 18, marginTop: 10 },
    newsletterBtn:{ alignItems: 'center', justifyContent: 'center', minHeight: 46, borderRadius: 14, backgroundColor: '#2f1d14', marginTop: 14 },
    newsletterBtnDisabled:{ opacity: 0.45 },
    newsletterBtnText:{ color: '#fff5eb', fontSize: 14, fontWeight: '800' },
    item:         { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 14, borderBottomWidth: 0.5, borderBottomColor: '#efe6dd' },
    iconWrap:     { width: 40, height: 40, borderRadius: 12, backgroundColor: PREMIUM_SURFACE_SOFT, alignItems: 'center', justifyContent: 'center' },
    label:        { fontSize: 15, fontWeight: '700', color: '#111' },
    sub:          { fontSize: 12, color: '#8c847d', marginTop: 2 },
    achievementOn: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#f0e5d9', padding: 10 },
    achievementOff:{ flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#f8f3ee', borderRadius: 12, borderWidth: 1, borderColor: '#efe4d7', padding: 10 },
    achievementIcon:{ fontSize: 22 },
    achievementIconOff:{ fontSize: 20, opacity: 0.75 },
    achievementTitle:{ fontSize: 13, fontWeight: '700', color: '#222' },
    achievementTitleOff:{ fontSize: 13, fontWeight: '700', color: '#8f7e70' },
    achievementDesc:{ fontSize: 12, color: '#777', marginTop: 1 },
    achievementToastWrap: { position: 'absolute', top: Platform.OS === 'ios' ? 52 : 16, left: 12, right: 12, zIndex: 9999 },
    achievementToastCard: { backgroundColor: '#2d1b14', borderRadius: 18, borderWidth: 1, borderColor: '#5f3c2c', paddingVertical: 14, paddingHorizontal: 14, shadowColor: '#000', shadowOpacity: 0.28, shadowRadius: 14, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
    achievementToastRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    achievementToastEmoji: { fontSize: 30, marginRight: 2 },
    achievementToastKicker: { fontSize: 11, fontWeight: '900', letterSpacing: 1, color: '#f4d7b9', marginBottom: 3 },
    achievementToastTitle: { fontSize: 16, fontWeight: '800', color: '#fff7ef', marginBottom: 2 },
    achievementToastDesc: { fontSize: 12, color: '#ead8c8' },
    achievementToastXpBadge: { backgroundColor: '#7a4b34', borderWidth: 1, borderColor: '#c58c63', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, marginLeft: 8 },
    achievementToastXpText: { fontSize: 11, fontWeight: '900', color: '#fff6ee', letterSpacing: 0.3 },
    emptyAchText: { color: '#8c847d', fontSize: 13, lineHeight: 19 },
    logoutBtn:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, borderRadius: 30, paddingVertical: 14, backgroundColor: '#2f1d14', borderWidth: 1, borderColor: '#513728', marginBottom: 4 },
    logoutText:   { fontSize: 15, fontWeight: '800', color: '#fff5eb' },
  });

  const caf = StyleSheet.create({
    loadBox:         { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, paddingTop: 60 },
    loadEmoji:       { fontSize: 48 },
    loadTitle:       { fontSize: 20, fontWeight: '700', color: '#111' },
    loadSub:         { fontSize: 14, color: THEME.text.secondary, textAlign: 'center' },
    errorBox:        { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 16 },
    errorTitle:      { fontSize: 22, fontWeight: '700', color: '#111' },
    errorText:       { fontSize: 15, color: THEME.text.secondary, textAlign: 'center', lineHeight: 22 },
    headerBox:       { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingTop: 20, paddingBottom: 12 },
    refreshBtn:      { width: 36, height: 36, borderRadius: 18, backgroundColor: PREMIUM_SURFACE_SOFT, alignItems: 'center', justifyContent: 'center' },
    card:            { marginHorizontal: 16, marginBottom: 16, backgroundColor: '#fff', borderRadius: 16, overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.07, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
    cardImgWrap:     { position: 'relative', height: 140 },
    cardImg:         { width: '100%', height: '100%' },
    cardNum:         { position: 'absolute', top: 10, left: 10, width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'center', justifyContent: 'center' },
    cardNumText:     { color: '#fff', fontWeight: '700', fontSize: 13 },
    cardEstado:      { position: 'absolute', top: 10, right: 10, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 4 },
    cardEstadoText:  { color: '#fff', fontSize: 11, fontWeight: '700' },
    cardInfo:        { padding: 12, gap: 4 },
    cardNombre:      { fontSize: 17, fontWeight: '800', color: '#111' },
    cardTipo:        { fontSize: 12, color: PREMIUM_ACCENT, fontWeight: '600', marginBottom: 2 },
    cardRatingRow:   { flexDirection: 'row', alignItems: 'center', gap: 3 },
    cardRatingNum:   { fontSize: 13, fontWeight: '700', color: '#333', marginLeft: 4 },
    cardReseñas:     { fontSize: 12, color: THEME.text.muted },
    cardTags:        { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
    cardTag:         { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: '#f5f5f5', borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 },
    cardTagText:     { fontSize: 11, color: '#555' },
    cardEspec:       { fontSize: 12, color: THEME.text.secondary, marginTop: 4, fontStyle: 'italic' },
    detHero:         { height: H * 0.38, position: 'relative' },
    detHeroGrad:     { position: 'absolute', bottom: 0, left: 0, right: 0, height: 160, backgroundColor: 'rgba(0,0,0,0.55)' },
    detPlaceholder:  { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#1a0a00', alignItems: 'center', justifyContent: 'center' },
    detPlaceholderEmoji: { fontSize: 72, opacity: 0.4 },
    cardPlaceholder: { width: '100%', height: '100%', backgroundColor: '#1a0a00', alignItems: 'center', justifyContent: 'center', padding: 12 },
    cardPlaceholderEmoji: { fontSize: 32, opacity: 0.5, marginBottom: 6 },
    cardPlaceholderNombre: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.7)', textAlign: 'center', lineHeight: 18 },
    detBack:         { position: 'absolute', top: 52, left: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center' },
    detNavBtn:       { position: 'absolute', top: 52, right: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: PREMIUM_ACCENT_DEEP, alignItems: 'center', justifyContent: 'center' },
    badgeEstado:     { position: 'absolute', top: 52, left: 70, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 },
    badgeEstadoText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    detOverlay:      { position: 'absolute', bottom: 16, left: 16, right: 16 },
    detNombre:       { fontSize: 24, fontWeight: '800', color: '#fff', marginBottom: 2 },
    detTipo:         { fontSize: 13, color: 'rgba(255,255,255,0.8)', marginBottom: 6 },
    detRatingRow:    { flexDirection: 'row', alignItems: 'center', gap: 4 },
    detRatingNum:    { fontSize: 15, fontWeight: '700', color: THEME.status.favorite, marginLeft: 4 },
    detReseñas:      { fontSize: 12, color: 'rgba(255,255,255,0.7)' },
    detBody:         { padding: 20 },
    detInfoRow:      { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20, backgroundColor: '#f9f9f9', borderRadius: 14, padding: 14 },
    detInfoItem:     { alignItems: 'center', gap: 4, minWidth: 56 },
    detInfoLabel:    { fontSize: 11, color: '#555', fontWeight: '600' },
    seccion:         { marginBottom: 20 },
    secTitulo:       { fontSize: 15, fontWeight: '700', color: '#111', marginBottom: 8 },
    secTexto:        { fontSize: 14, color: '#555', lineHeight: 22 },
    contactBtn:      { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 6 },
    contactText:     { fontSize: 14, color: PREMIUM_ACCENT_DEEP, fontWeight: '500' },
    resena:          { backgroundColor: '#f9f9f9', borderRadius: 12, padding: 12, marginBottom: 8 },
    resenaAutor:     { fontSize: 13, fontWeight: '700', color: '#111' },
    resenaTexto:     { fontSize: 13, color: '#555', marginTop: 4, lineHeight: 19 },
    item:    { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderBottomWidth: 0.5, borderBottomColor: THEME.border.soft },
    rank:    { width: 32, height: 32, borderRadius: 16, backgroundColor: PREMIUM_SURFACE_SOFT, alignItems: 'center', justifyContent: 'center' },
    rankNum: { fontSize: 14, fontWeight: '700', color: PREMIUM_ACCENT_DEEP },
    nombre:  { fontSize: 15, fontWeight: '600', color: '#111' },
    dir:     { fontSize: 12, color: THEME.text.secondary, marginTop: 2 },
    navBtn:  { padding: 8 },
    mapBox:  { marginBottom: 16 },
  });

  return { s, srch, q, det, scan, prf, pick, mas, caf };
}
