import { Platform, StyleSheet } from 'react-native';
import { PREMIUM_ACCENT, PREMIUM_ACCENT_DEEP, THEME } from '../constants/theme';

export const shared = StyleSheet.create({
  screen:        { flex: 1, backgroundColor: '#fff' },
  redBtn:        { backgroundColor: THEME.brand.primary, borderRadius: 30, padding: 16, alignItems: 'center', marginTop: 8, borderWidth: 1, borderColor: THEME.brand.primaryBorder, shadowColor: THEME.brand.primary, shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
  redBtnText:    { color: THEME.brand.onPrimary, fontWeight: '800', fontSize: 15, letterSpacing: 0.3 },
  label:         { fontSize: 12, fontWeight: '600', color: THEME.text.secondary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 8 },
  input:         { backgroundColor: '#f5f5f5', borderRadius: 12, padding: 14, fontSize: 15, color: '#111', marginBottom: 18 },
  sectionTitle:  { fontSize: 20, fontWeight: '700', color: '#111' },
  sectionSub:    { fontSize: 13, color: THEME.text.secondary, paddingHorizontal: 16, marginBottom: 14 },
  pageTitle:     { fontSize: 24, fontWeight: '700', color: '#111', marginBottom: 12 },
  empty:         { color: THEME.text.muted, textAlign: 'center', marginTop: 40, fontSize: 14 },
  backRow:       { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 20 },
  backText:      { color: PREMIUM_ACCENT_DEEP, fontSize: 15 },
  badgeRed:      { position: 'absolute', top: 8, left: 8, backgroundColor: PREMIUM_ACCENT, borderRadius: 12, paddingHorizontal: 7, paddingVertical: 3 },
  badgeText:     { color: '#fff', fontSize: 11, fontWeight: '700' },
  searchWrap:    { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, marginVertical: 10, backgroundColor: '#f5f5f5', borderRadius: 25, paddingHorizontal: 14, height: 44 },
  searchInput:   { flex: 1, fontSize: 15, color: '#222', marginLeft: 8 },
  faceIdBtn:     { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 16, padding: 14, borderWidth: 1.5, borderColor: THEME.brand.accentDeep, borderRadius: 30, backgroundColor: '#f9f2ea' },
  faceIdText:    { color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
  authSecondaryBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 14, padding: 14, borderWidth: 1.2, borderColor: '#dcc8b7', borderRadius: 30, backgroundColor: '#f9f2ea' },
  authSecondaryBtnText: { color: THEME.brand.accentDeep, fontWeight: '700', fontSize: 15 },
  // Packshot
  packshotFrame:     { backgroundColor: '#ffffff', borderRadius: 18, borderWidth: 1, borderColor: '#f1ece4', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 2, alignItems: 'center', justifyContent: 'center' },
  packshotInner:     { width: '100%', height: '100%', backgroundColor: '#fff', borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  packshotImage:     { width: '84%', height: '84%' },
  packshotHeroFrame: { width: '68%', height: '72%', borderRadius: 28, padding: 14 },
  packshotHeroImage: { width: '88%', height: '88%' },
  packshotCardFrame: { width: 132, height: 172, marginTop: 14, borderRadius: 18, padding: 10 },
  packshotCardImage: { width: '86%', height: '86%' },
  packshotListFrame: { width: 68, height: 88, borderRadius: 14, padding: 8 },
  packshotListImage: { width: '88%', height: '88%' },
  // Form
  formScroll:    { padding: 20, paddingTop: 52, paddingBottom: 50 },
  formTitle:     { fontSize: 26, fontWeight: '700', color: '#111', marginBottom: 20 },
  fotoEmpty:     { backgroundColor: '#f5f5f5', borderRadius: 14, height: 140, alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 20 },
  fotoEmptyText: { color: THEME.text.muted, fontSize: 14 },
  fotoFull:      { width: '100%', height: 200, borderRadius: 14, marginBottom: 8 },
  retake:        { color: PREMIUM_ACCENT_DEEP, fontSize: 13, textAlign: 'right', marginBottom: 20 },
});
