import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  welcomeScreen: {
    flex: 1,
    backgroundColor: '#f6efe7',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  welcomeAuraOne: {
    position: 'absolute',
    top: 90,
    right: -20,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(119, 82, 57, 0.08)',
  },
  welcomeAuraTwo: {
    position: 'absolute',
    bottom: 80,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 248, 241, 0.76)',
  },
  welcomeCard: {
    width: '100%',
    borderRadius: 30,
    backgroundColor: '#fffaf5',
    borderWidth: 1,
    borderColor: '#eadbce',
    paddingVertical: 34,
    paddingHorizontal: 22,
    alignItems: 'center',
    shadowColor: '#3a2416',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  welcomeTypeBox: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 130,
    gap: 6,
  },
  welcomeLineTop: {
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 3.2,
    color: '#5e4332',
    fontFamily: 'PlayfairDisplay_800ExtraBold',
  },
  welcomeLineBottom: {
    fontSize: 44,
    fontWeight: '900',
    letterSpacing: 4.2,
    color: '#1c120d',
    fontFamily: 'PlayfairDisplay_800ExtraBold',
  },
  welcomeSub: {
    fontSize: 10,
    color: '#6f5444',
    fontWeight: '800',
    letterSpacing: 2.1,
    textAlign: 'center',
    marginTop: 2,
  },
  welcomeCaption: {
    marginTop: 18,
    fontSize: 13,
    color: '#8a6d5b',
    fontWeight: '600',
    letterSpacing: 0.4,
    textAlign: 'center',
  },
});
