export const PAISES = [
  { label: '🇪🇸 España', value: 'España', flag: '🇪🇸' },
  { label: '🇲🇽 México', value: 'México', flag: '🇲🇽' },
  { label: '🇨🇴 Colombia', value: 'Colombia', flag: '🇨🇴' },
  { label: '🇦🇷 Argentina', value: 'Argentina', flag: '🇦🇷' },
  { label: '🇨🇱 Chile', value: 'Chile', flag: '🇨🇱' },
  { label: '🇵🇪 Perú', value: 'Perú', flag: '🇵🇪' },
  { label: '🇻🇪 Venezuela', value: 'Venezuela', flag: '🇻🇪' },
  { label: '🇪🇨 Ecuador', value: 'Ecuador', flag: '🇪🇨' },
  { label: '🇧🇴 Bolivia', value: 'Bolivia', flag: '🇧🇴' },
  { label: '🇵🇾 Paraguay', value: 'Paraguay', flag: '🇵🇾' },
  { label: '🇺🇾 Uruguay', value: 'Uruguay', flag: '🇺🇾' },
  { label: '🇧🇷 Brasil', value: 'Brasil', flag: '🇧🇷' },
  { label: '🇺🇸 Estados Unidos', value: 'Estados Unidos', flag: '🇺🇸' },
  { label: '🇬🇧 Reino Unido', value: 'Reino Unido', flag: '🇬🇧' },
  { label: '🇫🇷 Francia', value: 'Francia', flag: '🇫🇷' },
  { label: '🇩🇪 Alemania', value: 'Alemania', flag: '🇩🇪' },
  { label: '🇮🇹 Italia', value: 'Italia', flag: '🇮🇹' },
  { label: '🇵🇹 Portugal', value: 'Portugal', flag: '🇵🇹' },
  { label: '🇳🇱 Países Bajos', value: 'Países Bajos', flag: '🇳🇱' },
  { label: '🇧🇪 Bélgica', value: 'Bélgica', flag: '🇧🇪' },
  { label: '🇨🇭 Suiza', value: 'Suiza', flag: '🇨🇭' },
  { label: '🇸🇪 Suecia', value: 'Suecia', flag: '🇸🇪' },
  { label: '🇳🇴 Noruega', value: 'Noruega', flag: '🇳🇴' },
  { label: '🇩🇰 Dinamarca', value: 'Dinamarca', flag: '🇩🇰' },
  { label: '🇫🇮 Finlandia', value: 'Finlandia', flag: '🇫🇮' },
  { label: '🇵🇱 Polonia', value: 'Polonia', flag: '🇵🇱' },
  { label: '🇯🇵 Japón', value: 'Japón', flag: '🇯🇵' },
  { label: '🇰🇷 Corea del Sur', value: 'Corea del Sur', flag: '🇰🇷' },
  { label: '🇨🇳 China', value: 'China', flag: '🇨🇳' },
  { label: '🇦🇺 Australia', value: 'Australia', flag: '🇦🇺' },
  { label: '🇨🇦 Canadá', value: 'Canadá', flag: '🇨🇦' },
  { label: '🇲🇦 Marruecos', value: 'Marruecos', flag: '🇲🇦' },
  { label: '🇪🇹 Etiopía', value: 'Etiopía', flag: '🇪🇹' },
];

export const getFlagForPais = (pais) => PAISES.find((p) => p.value === pais)?.flag || '🌍';
